
const API_KEY = "8bbe3807862344f523a5e8a6532780f5";

let dailyWeather = [];
let hourlyWeather = [];
let weeklyWeather = [];
let unit = "celsius";
let celsius = true;
let rawHourlyTemps = [];
let rawDailyMin = [];
let rawDailyMax = [];


const moonPhasesHU = {
    "New Moon": "Újhold",
    "Waxing Crescent": "Növekvő sarló",
    "First Quarter": "Első negyed",
    "Waxing Gibbous": "Növekvő hold",
    "Full Moon": "Telihold",
    "Waning Gibbous": "Fogyó hold",
    "Last Quarter": "Utolsó negyed",
    "Waning Crescent": "Fogyó sarló"
};

const varosok = [
    "Szentendre",
    "Pilisszentlászló",
    "Budakalász",
    "Pomáz",
    "Csobánka",
    "Szigetmonostor",
    "Leányfalu",
    "Pócsmegyer",
    "Tahitótfalu",
    "Dunabogdány",
    "Kisoroszi",
    "Visegrád",
    "Dömös",
    "Pilismarót",
    "Érd",
    "Sóskút",
    "Pusztazámor",
    "Budaörs",
    "Törökbálint",
    "Diósd",
    "Biatorbágy",
    "Herceghalom",
    "Bicske",
    "Óbarok",
    "Csabdi",
    "Mány",
    "Szár",
    "Újbarok",
    "Szárliget",
    "Páty",
    "Zsámbék",
    "Tök",
    "Perbál",
    "Pilisjászfalu",
    "Piliscsaba",
    "Solymár",
    "Pilisszentiván",
    "Pilisvörösvár",
    "Tinnye",
    "Telki",
    "Remeteszőlős",
    "Etyek",
    "Budakeszi",
    "Budajenő",
    "Nagykovácsi",
    "Pilisszántó",
    "Üröm",
    "Pilisborosjenő",
    "Pilisszentkereszt",
    "Gödöllő",
    "Szada",
    "Veresegyház",
    "Erdőkertes",
    "Valkó",
    "Vácszentlászló",
    "Zsámbok",
    "Isaszeg",
    "Dány",
    "Pécel",
    "Dunakeszi",
    "Göd",
    "Sződliget",
    "Sződ",
    "Csörög",
    "Csömör",
    "Nagytarcsa",
    "Kistarcsa",
    "Kerepes",
    "Mogyoród",
    "Fót",
    "Csomád",
    "Őrbottyán",
    "Vácrátót",
    "Váchartyán",
    "Kisnémedi",
    "Püspökszilágy",
    "Vácduka",
    "Aszód",
    "Kartal",
    "Verseg",
    "Kálló",
    "Erdőkürt",
    "Erdőtarcsa",
    "Iklad",
    "Domony",
    "Galgamácsa",
    "Vácegres",
    "Váckisújfalu",
    "Bag",
    "Hévízgyörk",
    "Galgahévíz",
    "Tura",
    "Monor",
    "Péteri",
    "Vasad",
    "Csévharaszt",
    "Monorierdő",
    "Pánd",
    "Káva",
    "Bénye",
    "Gomba",
    "Vecsés",
    "Üllő",
    "Gyömrő",
    "Ecser",
    "Maglód",
    "Mende",
    "Sülysáp",
    "Kóka",
    "Úri",
    "Tápiószecső",
    "Tóalmás",
    "Tápióság",
    "Szentmártonkáta",
    "Szentlőrinckáta",
    "Ráckeve",
    "Lórév",
    "Szigetszentmiklós",
    "Halásztelek",
    "Szigethalom",
    "Tököl",
    "Szigetcsép",
    "Szigetszentmárton",
    "Szigetújfalu",
    "Szigetbecse",
    "Makád",
    "Dunaharaszti",
    "Taksony",
    "Dunavarsány",
    "Délegyháza",
    "Áporka",
    "Majosháza",
    "Kiskunlacháza",
    "Dömsöd",
    "Apaj",
    "Bugyi",
    "Alsónémedi",
    "Gyál",
    "Felsőpakony",
    "Ócsa",
    "Inárcs",
    "Kakucs",
    "Újhartyán",
    "Dabas",
    "Tatárszentgyörgy",
    "Hernád",
    "Örkény",
    "Pusztavacs",
    "Táborfalva",
    "Dunaújváros",
    "Nagyvenyim",
    "Mezőfalva",
    "Daruszentmiklós",
    "Előszállás",
    "Nagykarácsony",
    "Baracs",
    "Kisapostag",
    "Perkáta",
    "Szabadegyháza",
    "Sárosd",
    "Hantos",
    "Nagylók",
    "Százhalombatta",
    "Ercsi",
    "Iváncsa",
    "Beloiannisz",
    "Besnyő",
    "Adony",
    "Kulcs",
    "Rácalmás",
    "Tárnok",
    "Martonvásár",
    "Tordas",
    "Gyúró",
    "Ráckeresztúr",
    "Baracska",
    "Kajászó",
    "Vál",
    "Kápolnásnyék",
    "Pázmánd",
    "Vereb",
    "Velence",
    "Gárdony",
    "Pusztaszabolcs",
    "Esztergom",
    "Dorog",
    "Kesztölc",
    "Leányvár",
    "Piliscsév",
    "Csolnok",
    "Dág",
    "Sárisáp",
    "Nagysáp",
    "Bajna",
    "Epöl",
    "Máriahalom",
    "Úny",
    "Annavölgy",
    "Tokod",
    "Tokodaltáró",
    "Bajót",
    "Tát",
    "Mogyorósbánya",
    "Nyergesújfalu",
    "Lábatlan",
    "Süttő",
    "Neszmély",
    "Dunaalmás",
    "Vác",
    "Nőtincs",
    "Ősagárd",
    "Felsőpetény",
    "Kosd",
    "Rád",
    "Penc",
    "Csővár",
    "Keszeg",
    "Alsópetény",
    "Nézsa",
    "Legénd",
    "Verőce",
    "Kismaros",
    "Szokolya",
    "Kóspallag",
    "Nagymaros",
    "Zebegény",
    "Szob",
    "Márianosztra",
    "Ipolydamásd",
    "Letkés",
    "Ipolytölgyes",
    "Nagybörzsöny",
    "Vámosmikola",
    "Tésa",
    "Perőcsény",
    "Kemence",
    "Bernecebaráti",
    "Szendehely",
    "Berkenye",
    "Nógrád",
    "Diósjenő",
    "Borsosberény",
    "Nagyoroszi",
    "Drégelypalánk",
    "Hont",
    "Patak",
    "Dejtár",
    "Rétság",
    "Tereske",
    "Bánk",
    "Romhány",
    "Kétbodony",
    "Kisecset",
    "Szente",
    "Szátok",
    "Tolmács",
    "Horpács",
    "Pusztaberki",
    "Érsekvadkert",
    "Balassagyarmat",
    "Ipolyszög",
    "Patvarc",
    "Ipolyvece",
    "Őrhalom",
    "Hugyag",
    "Csitár",
    "Iliny",
    "Nógrádmarcal",
    "Cserhátsurány",
    "Herencsény",
    "Csesztve",
    "Galgagyörk",
    "Püspökhatvan",
    "Acsa",
    "Nógrádsáp",
    "Galgaguta",
    "Bercel",
    "Vanyarc",
    "Nógrádkövesd",
    "Szécsénke",
    "Becske",
    "Magyarnándor",
    "Cserháthaláp",
    "Debercsény",
    "Terény",
    "Szanda",
    "Mohora",
    "Szügy",
    "Cegléd",
    "Tápiószentmárton",
    "Nyársapát",
    "Csemő",
    "Pilis",
    "Nyáregyháza",
    "Újlengyel",
    "Albertirsa",
    "Dánszentmiklós",
    "Mikebuda",
    "Ceglédbercel",
    "Abony",
    "Kőröstetétlen",
    "Jászkarajenő",
    "Törtel",
    "Nagykőrös",
    "Kocsér",
    "Nagykáta",
    "Tápióbicske",
    "Farmos",
    "Tápiószele",
    "Tápiógyörgye",
    "Újszilvás",
    "Tápiószőlős",
    "Tatabánya",
    "Gyermely",
    "Szomor",
    "Vértessomló",
    "Várgesztes",
    "Tarján",
    "Héreg",
    "Vértestolna",
    "Tardos",
    "Baj",
    "Vértesszőlős",
    "Oroszlány",
    "Környe",
    "Kecskéd",
    "Kömlőd",
    "Dad",
    "Bokod",
    "Szákszend",
    "Császár",
    "Vérteskethely",
    "Bakonysárkány",
    "Aka",
    "Kisbér",
    "Ászár",
    "Kerékteleki",
    "Bársonyos",
    "Bakonyszombathely",
    "Bakonybánk",
    "Réde",
    "Ácsteszér",
    "Csatka",
    "Súr",
    "Tata",
    "Szomód",
    "Dunaszentmiklós",
    "Kocs",
    "Naszály",
    "Komárom",
    "Mocsa",
    "Almásfüzitő",
    "Ács",
    "Nagyigmánd",
    "Bábolna",
    "Bana",
    "Tárkány",
    "Csép",
    "Ete",
    "Kisigmánd",
    "Csém",
    "Hatvan",
    "Kerekharaszt",
    "Heréd",
    "Nagykökényes",
    "Ecséd",
    "Hort",
    "Csány",
    "Boldog",
    "Lőrinci",
    "Petőfibánya",
    "Zagyvaszántó",
    "Apc",
    "Rózsaszentmárton",
    "Szűcsi",
    "Gyöngyöspata",
    "Gyöngyöstarján",
    "Héhalom",
    "Palotás",
    "Egyházasdengeleg",
    "Szirák",
    "Bér",
    "Kisbágyon",
    "Buják",
    "Szarvasgede",
    "Csécse",
    "Ecseg",
    "Kozárd",
    "Pásztó",
    "Jobbágyi",
    "Szurdokpüspöki",
    "Cserhátszentiván",
    "Bokor",
    "Kutasó",
    "Felsőtold",
    "Garáb",
    "Mátraszőlős",
    "Alsótold",
    "Bátonyterenye",
    "Tar",
    "Sámsonháza",
    "Nagybárkány",
    "Kisbárkány",
    "Márkháza",
    "Mátraverebély",
    "Salgótarján",
    "Somoskőújfalu",
    "Cered",
    "Zabar",
    "Szilaspogony",
    "Bárna",
    "Kazár",
    "Vizslás",
    "Lucfalva",
    "Nagykeresztúr",
    "Sóshartyán",
    "Nógrádmegyer",
    "Magyargéc",
    "Piliny",
    "Szécsényfelfalu",
    "Etes",
    "Karancsberény",
    "Ipolytarnóc",
    "Mátraszele",
    "Mátranovák",
    "Mátraterenye",
    "Rákóczibánya",
    "Nemti",
    "Dorogháza",
    "Szuha",
    "Mátramindszent",
    "Kishartyán",
    "Ságújfalu",
    "Karancsság",
    "Szalmatercs",
    "Endrefalva",
    "Szécsény",
    "Nagylóc",
    "Hollókő",
    "Rimóc",
    "Varsány",
    "Nógrádsipek",
    "Karancsalja",
    "Karancslapujtő",
    "Karancskeszi",
    "Mihálygerge",
    "Egyházasgerge",
    "Litke",
    "Nógrádszakál",
    "Ludányhalászi",
    "Gyöngyös",
    "Gyöngyösoroszi",
    "Gyöngyöshalász",
    "Atkár",
    "Nagyréde",
    "Gyöngyössolymos",
    "Mátraszentimre",
    "Parád",
    "Parádsasvár",
    "Bodony",
    "Recsk",
    "Mátraderecske",
    "Mátraballa",
    "Ivád",
    "Pétervására",
    "Erdőkövesd",
    "Istenmezeje",
    "Váraszó",
    "Fedémes",
    "Kisfüzes",
    "Bükkszenterzsébet",
    "Tarnalelesz",
    "Szentdomonkos",
    "Abasár",
    "Pálosvörösmart",
    "Markaz",
    "Domoszló",
    "Kisnána",
    "Vécs",
    "Visonta",
    "Halmajugra",
    "Ludas",
    "Detk",
    "Karácsond",
    "Nagyfüged",
    "Tarnazsadány",
    "Tarnaméra",
    "Vámosgyörk",
    "Adács",
    "Visznek",
    "Tarnaörs",
    "Erk",
    "Zaránk",
    "Eger",
    "Egerbakta",
    "Hevesaranyos",
    "Szarvaskő",
    "Felsőtárkány",
    "Noszvaj",
    "Ostoros",
    "Novaj",
    "Egerszólát",
    "Tarnaszentmária",
    "Sirok",
    "Terpes",
    "Szajla",
    "Bükkszék",
    "Bátor",
    "Egerbocs",
    "Egercsehi",
    "Szúcs",
    "Bekölce",
    "Mikófalva",
    "Mónosbél",
    "Bélapátfalva",
    "Bükkszentmárton",
    "Balaton",
    "Szilvásvárad",
    "Nagyvisnyó",
    "Kál",
    "Verpelét",
    "Feldebrő",
    "Aldebrő",
    "Tófalu",
    "Kápolna",
    "Kompolt",
    "Nagyút",
    "Erdőtelek",
    "Tenk",
    "Heves",
    "Boconád",
    "Tarnabod",
    "Átány",
    "Kömlő",
    "Besenyőtelek",
    "Dormánd",
    "Mezőtárkány",
    "Szihalom",
    "Mezőszemere",
    "Egerfarmos",
    "Pély",
    "Tarnaszentmiklós",
    "Hevesvezekény",
    "Kisköre",
    "Tiszanána",
    "Sarud",
    "Újlőrincfalva",
    "Poroszló",
    "Füzesabony",
    "Egerszalók",
    "Demjén",
    "Kerecsend",
    "Maklár",
    "Nagytálya",
    "Andornaktálya",
    "Mezőkövesd",
    "Szomolya",
    "Bogács",
    "Cserépfalu",
    "Bükkzsérc",
    "Tard",
    "Cserépváralja",
    "Szentistván",
    "Mezőnyárád",
    "Bükkábrány",
    "Tibolddaróc",
    "Kács",
    "Sály",
    "Borsodgeszt",
    "Vatta",
    "Emőd",
    "Nyékládháza",
    "Mályi",
    "Mezőkeresztes",
    "Csincse",
    "Mezőnagymihály",
    "Gelej",
    "Mezőcsát",
    "Tiszakeszi",
    "Igrici",
    "Egerlövő",
    "Borsodivánka",
    "Négyes",
    "Tiszavalk",
    "Tiszabábolna",
    "Tiszadorogma",
    "Ároktő",
    "Miskolc",
    "Ónod",
    "Muhi",
    "Kistokaj",
    "Bükkaranyos",
    "Harsány",
    "Kisgyőr",
    "Bükkszentkereszt",
    "Répáshuta",
    "Felsőzsolca",
    "Onga",
    "Hernádkak",
    "Hernádnémeti",
    "Tiszalúc",
    "Alsózsolca",
    "Sajólád",
    "Sajópetri",
    "Bőcs",
    "Berzék",
    "Sajóhídvég",
    "Köröm",
    "Girincs",
    "Kiscsécs",
    "Kesznyéten",
    "Tiszaújváros",
    "Sajóörös",
    "Tiszapalkonya",
    "Hejőkürt",
    "Tiszatarján",
    "Oszlár",
    "Nemesbikk",
    "Hejőbába",
    "Hejőpapi",
    "Hejőszalonta",
    "Szakáld",
    "Hejőkeresztúr",
    "Nagycsécs",
    "Sajószöged",
    "Ózd",
    "Farkaslyuk",
    "Uppony",
    "Borsodszentgyörgy",
    "Hangony",
    "Domaháza",
    "Kissikátor",
    "Putnok",
    "Dubicsány",
    "Vadna",
    "Sajógalgóc",
    "Nagybarca",
    "Bánhorváti",
    "Dédestapolcsány",
    "Tardona",
    "Mályinka",
    "Nekézseny",
    "Csokvaomány",
    "Csernely",
    "Bükkmogyorósd",
    "Lénárddaróc",
    "Sajónémeti",
    "Sajópüspöki",
    "Bánréve",
    "Hét",
    "Sajóvelezd",
    "Sajómercse",
    "Királd",
    "Borsodbóta",
    "Sáta",
    "Arló",
    "Járdánháza",
    "Borsodnádasd",
    "Kazincbarcika",
    "Berente",
    "Szirmabesenyő",
    "Sajóvámos",
    "Sajósenye",
    "Arnót",
    "Sajópálfala",
    "Gesztely",
    "Újcsanálos",
    "Sóstófalva",
    "Alsódobsza",
    "Megyaszó",
    "Sajókaza",
    "Sajóivánka",
    "Felsőnyárád",
    "Dövény",
    "Jákfalva",
    "Felsőkelecsény",
    "Zubogy",
    "Ragály",
    "Trizs",
    "Imola",
    "Zádorfalva",
    "Alsószuha",
    "Szuhafő",
    "Kelemér",
    "Gömörszőlős",
    "Serényfalva",
    "Szuhakálló",
    "Kurityán",
    "Rudabánya",
    "Szuhogy",
    "Felsőtelekes",
    "Alsótelekes",
    "Kánó",
    "Izsófalva",
    "Rudolftelep",
    "Ormosbánya",
    "Múcsony",
    "Szendrőlád",
    "Szendrő",
    "Galvács",
    "Abod",
    "Szalonna",
    "Meszes",
    "Martonyi",
    "Perkupa",
    "Varbóc",
    "Szőlősardó",
    "Égerszög",
    "Teresztenye",
    "Jósvafő",
    "Aggtelek",
    "Szin",
    "Szinpetri",
    "Tornakápolna",
    "Szögliget",
    "Bódvaszilas",
    "Bódvarákó",
    "Komjáti",
    "Tornabarakony",
    "Tornaszentandrás",
    "Tornanádaska",
    "Hidvégardó",
    "Becskeháza",
    "Bódvalenke",
    "Tornaszentjakab",
    "Sajószentpéter",
    "Sajókápolna",
    "Sajólászlófalva",
    "Kondó",
    "Radostyán",
    "Parasznya",
    "Varbó",
    "Alacska",
    "Edelény",
    "Balajt",
    "Damak",
    "Ládbesenyő",
    "Lak",
    "Hegymeg",
    "Irota",
    "Szakácsi",
    "Tomor",
    "Sajókeresztúr",
    "Sajóbábony",
    "Sajóecseg",
    "Boldva",
    "Ziliz",
    "Hangács",
    "Nyomár",
    "Borsodszirák",
    "Szikszó",
    "Selyeb",
    "Abaújszolnok",
    "Nyésta",
    "Alsóvadász",
    "Homrogd",
    "Monaj",
    "Kupa",
    "Felsővadász",
    "Gadna",
    "Abaújlak",
    "Gagyvendégi",
    "Gagybátor",
    "Krasznokvajda",
    "Büttös",
    "Kány",
    "Keresztéte",
    "Pamlény",
    "Perecse",
    "Szászfa",
    "Rakaca",
    "Debréte",
    "Viszló",
    "Rakacaszend",
    "Kázsmárk",
    "Léh",
    "Rásonysápberencs",
    "Detek",
    "Beret",
    "Baktakék",
    "Felsőgagy",
    "Alsógagy",
    "Csenyéte",
    "Gagyapáti",
    "Aszaló",
    "Halmaj",
    "Kiskinizs",
    "Nagykinizs",
    "Szentistvánbaksa",
    "Hernádkércs",
    "Felsődobsza",
    "Csobád",
    "Forró",
    "Ináncs",
    "Hernádszentandrás",
    "Pere",
    "Hernádbűd",
    "Gibárt",
    "Fancsal",
    "Encs",
    "Szalaszend",
    "Fulókércs",
    "Fáj",
    "Szemere",
    "Litka",
    "Méra",
    "Novajidrány",
    "Garadna",
    "Hernádvécse",
    "Hernádpetri",
    "Pusztaradvány",
    "Hernádszurdok",
    "Hidasnémeti",
    "Tornyosnémeti",
    "Abaújszántó",
    "Baskó",
    "Sima",
    "Abaújkér",
    "Abaújalpár",
    "Boldogkőújfalu",
    "Boldogkőváralja",
    "Arka",
    "Korlát",
    "Hernádcéce",
    "Vizsoly",
    "Vilmány",
    "Hejce",
    "Fony",
    "Mogyoróska",
    "Regéc",
    "Göncruszka",
    "Gönc",
    "Telkibánya",
    "Zsujta",
    "Abaújvár",
    "Pányok",
    "Kéked",
    "Szerencs",
    "Bekecs",
    "Legyesbénye",
    "Monok",
    "Golop",
    "Tállya",
    "Rátka",
    "Mád",
    "Tokaj",
    "Tarcal",
    "Bodrogkeresztúr",
    "Bodrogkisfalud",
    "Szegi",
    "Szegilong",
    "Taktaszada",
    "Taktaharkány",
    "Taktakenéz",
    "Prügy",
    "Taktabáj",
    "Csobaj",
    "Tiszatardos",
    "Tiszaladány",
    "Mezőzombor",
    "Erdőbénye",
    "Olaszliszka",
    "Tolcsva",
    "Erdőhorváti",
    "Háromhuta",
    "Komlóska",
    "Vámosújfalu",
    "Sárazsadány",
    "Bodrogolaszi",
    "Sárospatak",
    "Györgytarló",
    "Kenézlő",
    "Viss",
    "Zalkod",
    "Hercegkút",
    "Makkoshotyka",
    "Vajdácska",
    "Karos",
    "Karcsa",
    "Pácin",
    "Nagyrozvágy",
    "Kisrozvágy",
    "Lácacséke",
    "Tiszakarád",
    "Tiszacsermely",
    "Cigánd",
    "Ricse",
    "Semjén",
    "Révleányvár",
    "Zemplénagárd",
    "Dámóc",
    "Sátoraljaújhely",
    "Alsóberecki",
    "Felsőberecki",
    "Bodroghalom",
    "Mikóháza",
    "Alsóregmec",
    "Felsőregmec",
    "Vilyvitány",
    "Kovácsvágás",
    "Vágáshuta",
    "Füzérradvány",
    "Pálháza",
    "Bózsva",
    "Filkeháza",
    "Füzérkajata",
    "Kishuta",
    "Nagyhuta",
    "Pusztafalu",
    "Füzér",
    "Füzérkomlós",
    "Nyíri",
    "Hollóháza",
    "Debrecen",
    "Balmazújváros",
    "Nagyhegyes",
    "Újszentmargita",
    "Tiszacsege",
    "Egyek",
    "Hortobágy",
    "Görbeháza",
    "Hajdúnánás",
    "Hajdúdorog",
    "Polgár",
    "Folyás",
    "Újtikos",
    "Tiszagyulaháza",
    "Berettyóújfalu",
    "Biharkeresztes",
    "Bojt",
    "Ártánd",
    "Berekböszörmény",
    "Told",
    "Mezőpeterd",
    "Váncsod",
    "Szentpéterszeg",
    "Gáborján",
    "Hencida",
    "Esztár",
    "Pocsaj",
    "Kismarja",
    "Nagykereki",
    "Bedő",
    "Derecske",
    "Tépe",
    "Konyár",
    "Mezősas",
    "Körösszegapáti",
    "Körösszakál",
    "Magyarhomorog",
    "Komádi",
    "Furta",
    "Zsáka",
    "Vekerd",
    "Darvas",
    "Csökmő",
    "Újiráz",
    "Püspökladány",
    "Báránd",
    "Szerep",
    "Bakonszeg",
    "Sárrétudvari",
    "Biharnagybajom",
    "Nagyrábé",
    "Bihartorda",
    "Bihardancsháza",
    "Sáp",
    "Földes",
    "Nádudvar",
    "Kaba",
    "Tetétlen",
    "Hajdúszoboszló",
    "Ebes",
    "Hajdúszovát",
    "Hajdúböszörmény",
    "Bököny",
    "Geszteréd",
    "Balkány",
    "Szakoly",
    "Biri",
    "Bocskaikert",
    "Hajdúhadház",
    "Téglás",
    "Újfehértó",
    "Érpatak",
    "Hajdúsámson",
    "Nyíradony",
    "Nyíracsád",
    "Nyírmártonfalva",
    "Nyírábrány",
    "Fülöp",
    "Penészlek",
    "Mikepércs",
    "Sáránd",
    "Hajdúbagos",
    "Hosszúpályi",
    "Monostorpályi",
    "Létavértes",
    "Kokad",
    "Álmosd",
    "Bagamér",
    "Vámospércs",
    "Újléta",
    "Nyírbátor",
    "Nyírgyulaj",
    "Nagykálló",
    "Kállósemjén",
    "Kisléta",
    "Máriapócs",
    "Pócspetri",
    "Nyírcsászári",
    "Nyírderzs",
    "Nyírkáta",
    "Hodász",
    "Kántorjánosi",
    "Őr",
    "Jármi",
    "Papos",
    "Nyírvasvári",
    "Terem",
    "Bátorliget",
    "Vállaj",
    "Mérk",
    "Tiborszállás",
    "Fábiánháza",
    "Nagyecsed",
    "Nyírcsaholy",
    "Nyírbogát",
    "Nyírgelse",
    "Nyírmihálydi",
    "Nyírlugos",
    "Nyírbéltek",
    "Ömböly",
    "Encsencs",
    "Piricse",
    "Nyírpilis",
    "Nyíregyháza",
    "Kálmánháza",
    "Tiszavasvári",
    "Szorgalmatos",
    "Nagycserkesz",
    "Tiszalök",
    "Tiszadada",
    "Tiszadob",
    "Nyírtelek",
    "Tiszanagyfalu",
    "Tiszaeszlár",
    "Rakamaz",
    "Timár",
    "Szabolcs",
    "Balsa",
    "Gávavencsellő",
    "Tiszabercel",
    "Paszab",
    "Kótaj",
    "Buj",
    "Ibrány",
    "Nagyhalász",
    "Tiszatelek",
    "Beszterec",
    "Újdombrád",
    "Dombrád",
    "Tiszakanyár",
    "Kékcse",
    "Döge",
    "Szabolcsveresmart",
    "Kemecse",
    "Vasmegyer",
    "Tiszarád",
    "Nyírbogdány",
    "Kék",
    "Demecser",
    "Gégény",
    "Berkesz",
    "Nyírtass",
    "Pátroha",
    "Ajak",
    "Rétközberencs",
    "Nyírpazony",
    "Nyírtura",
    "Sényő",
    "Székely",
    "Nyíribrony",
    "Ramocsaháza",
    "Nyírkércs",
    "Nyírjákó",
    "Petneháza",
    "Laskod",
    "Nyírkarász",
    "Gyulaháza",
    "Anarcs",
    "Szabolcsbáka",
    "Napkor",
    "Apagy",
    "Nyírtét",
    "Levelek",
    "Magy",
    "Besenyőd",
    "Ófehértó",
    "Baktalórántháza",
    "Vaja",
    "Rohod",
    "Nyírmada",
    "Pusztadobos",
    "Ilk",
    "Gemzse",
    "Kisvárda",
    "Jéke",
    "Fényeslitke",
    "Komoró",
    "Tuzsér",
    "Tiszabezdéd",
    "Záhony",
    "Győröcske",
    "Zsurk",
    "Tiszaszentmárton",
    "Pap",
    "Nyírlövő",
    "Lövőpetri",
    "Aranyosapáti",
    "Újkenéz",
    "Mezőladány",
    "Tornyospálca",
    "Benk",
    "Mándok",
    "Tiszamogyorós",
    "Eperjeske",
    "Mátészalka",
    "Szamoskér",
    "Nyírmeggyes",
    "Tunyogmatolcs",
    "Cégénydányád",
    "Gyügye",
    "Szamosújlak",
    "Szamossályi",
    "Hermánszeg",
    "Kisnamény",
    "Darnó",
    "Jánkmajtis",
    "Csegöld",
    "Csengersima",
    "Szamosbecs",
    "Szamostatárfalva",
    "Kocsord",
    "Győrtelek",
    "Géberjén",
    "Fülpösdaróc",
    "Ököritófülpös",
    "Rápolt",
    "Porcsalma",
    "Tyukod",
    "Ura",
    "Csengerújfalu",
    "Csenger",
    "Komlódtótfalu",
    "Pátyod",
    "Szamosangyalos",
    "Vásárosnamény",
    "Kisvarsány",
    "Nagyvarsány",
    "Gyüre",
    "Ópályi",
    "Nyírparasznya",
    "Nagydobos",
    "Szamosszeg",
    "Olcsva",
    "Tiszaszalka",
    "Tiszavid",
    "Tiszaadony",
    "Tiszakerecseny",
    "Mátyus",
    "Lónya",
    "Jánd",
    "Gulács",
    "Hetefejércse",
    "Csaroda",
    "Tákos",
    "Fehérgyarmat",
    "Nábrád",
    "Kérsemjén",
    "Panyola",
    "Olcsvaapáti",
    "Kisar",
    "Tivadar",
    "Nagyar",
    "Tarpa",
    "Márokpapi",
    "Beregsurány",
    "Beregdaróc",
    "Gelénes",
    "Vámosatya",
    "Barabás",
    "Penyige",
    "Mánd",
    "Nemesborzova",
    "Kömörő",
    "Túristvándi",
    "Szatmárcseke",
    "Tiszakóród",
    "Tiszacsécse",
    "Milota",
    "Tiszabecs",
    "Uszka",
    "Magosliget",
    "Sonkád",
    "Botpalád",
    "Kispalád",
    "Zsarolyán",
    "Nagyszekeres",
    "Kisszekeres",
    "Fülesd",
    "Kölcse",
    "Vámosoroszi",
    "Csaholc",
    "Túrricse",
    "Tisztaberek",
    "Rozsály",
    "Gacsály",
    "Császló",
    "Zajta",
    "Méhtelek",
    "Garbolc",
    "Nagyhódos",
    "Kishódos",
    "Szolnok",
    "Zagyvarékas",
    "Újszász",
    "Szászberek",
    "Jászalsószentgyörgy",
    "Jászladány",
    "Tiszasüly",
    "Kőtelek",
    "Hunyadfalva",
    "Csataszög",
    "Nagykörű",
    "Besenyszög",
    "Szajol",
    "Tiszatenyő",
    "Kengyel",
    "Rákócziújfalu",
    "Rákóczifalva",
    "Tószeg",
    "Tiszavárkony",
    "Vezseny",
    "Tiszajenő",
    "Jászberény",
    "Jászfelsőszentgyörgy",
    "Jászjákóhalma",
    "Jászdózsa",
    "Jászárokszállás",
    "Jászágó",
    "Pusztamonostor",
    "Jászfényszaru",
    "Jászapáti",
    "Jászivány",
    "Jászszentandrás",
    "Jászkisér",
    "Jásztelek",
    "Alattyán",
    "Jánoshida",
    "Jászboldogháza",
    "Törökszentmiklós",
    "Tiszapüspöki",
    "Örményes",
    "Fegyvernek",
    "Tiszabő",
    "Tiszagyenda",
    "Tiszaroff",
    "Tiszabura",
    "Abádszalók",
    "Tiszaderzs",
    "Tiszaszőlős",
    "Karcag",
    "Berekfürdő",
    "Kisújszállás",
    "Kunmadaras",
    "Tiszaszentimre",
    "Tomajmonostora",
    "Kenderes",
    "Kunhegyes",
    "Tiszafüred",
    "Tiszaigar",
    "Tiszaörs",
    "Nagyiván",
    "Mezőtúr",
    "Kétpó",
    "Kuncsorba",
    "Túrkeve",
    "Tiszaföldvár",
    "Martfű",
    "Kunszentmárton",
    "Öcsöd",
    "Mesterszállás",
    "Mezőhék",
    "Cibakháza",
    "Nagyrév",
    "Tiszainoka",
    "Cserkeszőlő",
    "Tiszakürt",
    "Tiszasas",
    "Csépa",
    "Szelevény",
    "Gyomaendrőd",
    "Dévaványa",
    "Ecsegfalva",
    "Körösladány",
    "Szeghalom",
    "Füzesgyarmat",
    "Kertészsziget",
    "Bucsa",
    "Vésztő",
    "Okány",
    "Körösújfalu",
    "Zsadány",
    "Biharugra",
    "Körösnagyharsány",
    "Szarvas",
    "Csabacsűd",
    "Kardos",
    "Kondoros",
    "Hunya",
    "Örménykút",
    "Békésszentandrás",
    "Békéscsaba",
    "Csabaszabadi",
    "Csárdaszállás",
    "Köröstarcsa",
    "Doboz",
    "Békés",
    "Tarhos",
    "Bélmegyer",
    "Mezőberény",
    "Újkígyós",
    "Csanádapáca",
    "Medgyesbodzás",
    "Pusztaottlaka",
    "Medgyesegyháza",
    "Magyarbánhegyes",
    "Nagybánhegyes",
    "Murony",
    "Kamut",
    "Kétsoprony",
    "Telekgerendás",
    "Gyula",
    "Szabadkígyós",
    "Sarkad",
    "Kötegyán",
    "Méhkerék",
    "Újszalonta",
    "Sarkadkeresztúr",
    "Mezőgyán",
    "Geszt",
    "Kétegyháza",
    "Elek",
    "Lőkösháza",
    "Kevermes",
    "Dombiratos",
    "Kunágota",
    "Almáskamarás",
    "Nagykamarás",
    "Mezőkovácsháza",
    "Végegyháza",
    "Mezőhegyes",
    "Battonya",
    "Dombegyház",
    "Kisdombegyház",
    "Magyardombegyház",
    "Orosháza",
    "Pusztaföldvár",
    "Csorvás",
    "Gerendás",
    "Nagyszénás",
    "Gádoros",
    "Tótkomlós",
    "Kardoskút",
    "Békéssámson",
    "Kaszaper",
    "Kecskemét",
    "Szentkirály",
    "Nyárlőrinc",
    "Városföld",
    "Helvécia",
    "Ballószög",
    "Kerekegyháza",
    "Fülöpháza",
    "Kunbaracs",
    "Ladánybene",
    "Lajosmizse",
    "Felsőlajos",
    "Tiszakécske",
    "Tiszaug",
    "Lakitelek",
    "Izsák",
    "Páhi",
    "Ágasegyháza",
    "Orgovány",
    "Jakabszállás",
    "Szabadszállás",
    "Fülöpszállás",
    "Szalkszentmárton",
    "Dunavecse",
    "Apostag",
    "Kunszentmiklós",
    "Kunpeszér",
    "Kunadacs",
    "Tass",
    "Kiskunfélegyháza",
    "Gátér",
    "Pálmonostora",
    "Petőfiszállás",
    "Bugac",
    "Bugacpusztaháza",
    "Kunszállás",
    "Fülöpjakab",
    "Kiskunmajsa",
    "Szank",
    "Móricgát",
    "Jászszentlászló",
    "Kömpöc",
    "Csólyospálos",
    "Harkakötöny",
    "Kiskőrös",
    "Kaskantyú",
    "Akasztó",
    "Csengőd",
    "Soltszentimre",
    "Tabdi",
    "Soltvadkert",
    "Bócsa",
    "Tázlár",
    "Kecel",
    "Imrehegy",
    "Császártöltés",
    "Kalocsa",
    "Öregcsertő",
    "Solt",
    "Újsolt",
    "Dunaegyháza",
    "Dunatetétlen",
    "Harta",
    "Dunapataj",
    "Foktő",
    "Uszód",
    "Dunaszentbenedek",
    "Géderlak",
    "Ordas",
    "Szakmár",
    "Újtelek",
    "Homokmégy",
    "Drágszél",
    "Miske",
    "Hajós",
    "Nemesnádudvar",
    "Sükösd",
    "Érsekcsanád",
    "Érsekhalma",
    "Bátya",
    "Fajsz",
    "Dusnok",
    "Kiskunhalas",
    "Zsana",
    "Balotaszállás",
    "Kunfehértó",
    "Pirtó",
    "Kisszállás",
    "Tompa",
    "Kelebia",
    "Csikéria",
    "Bácsszőlős",
    "Bácsalmás",
    "Kunbaja",
    "Jánoshalma",
    "Kéleshalom",
    "Borota",
    "Rém",
    "Felsőszentiván",
    "Csávoly",
    "Mélykút",
    "Tataháza",
    "Mátételke",
    "Bácsbokod",
    "Bácsborsód",
    "Katymár",
    "Madaras",
    "Baja",
    "Bácsszentgyörgy",
    "Szeremle",
    "Dunafalva",
    "Vaskút",
    "Gara",
    "Csátalja",
    "Dávod",
    "Hercegszántó",
    "Nagybaracska",
    "Bátmonostor",
    "Szentes",
    "Nagytőke",
    "Derekegyház",
    "Nagymágocs",
    "Árpádhalom",
    "Eperjes",
    "Fábiánsebestyén",
    "Mindszent",
    "Szegvár",
    "Mártély",
    "Csongrád",
    "Felgyő",
    "Tömörkény",
    "Csanytelek",
    "Tiszaalpár",
    "Szeged",
    "Algyő",
    "Újszentiván",
    "Kübekháza",
    "Tiszasziget",
    "Röszke",
    "Kistelek",
    "Sándorfalva",
    "Szatymaz",
    "Balástya",
    "Csengele",
    "Dóc",
    "Ópusztaszer",
    "Baks",
    "Pusztaszer",
    "Deszk",
    "Klárafalva",
    "Ferencszállás",
    "Kiszombor",
    "Domaszék",
    "Mórahalom",
    "Ásotthalom",
    "Öttömös",
    "Pusztamérges",
    "Ruzsa",
    "Zákányszék",
    "Zsombó",
    "Forráskút",
    "Üllés",
    "Bordány",
    "Hódmezővásárhely",
    "Székkutas",
    "Makó",
    "Királyhegyes",
    "Kövegy",
    "Csanádpalota",
    "Pitvaros",
    "Csanádalberti",
    "Ambrózfalva",
    "Nagyér",
    "Maroslele",
    "Földeák",
    "Óföldeák",
    "Apátfalva",
    "Magyarcsanád",
    "Nagylak",
    "Sárbogárd",
    "Alap",
    "Alsószentiván",
    "Cece",
    "Sáregres",
    "Igar",
    "Mezőszilas",
    "Dunaföldvár",
    "Bölcske",
    "Madocsa",
    "Paks",
    "Pusztahencse",
    "Németkér",
    "Vajta",
    "Pálfa",
    "Bikács",
    "Nagydorog",
    "Györköny",
    "Sárszentlőrinc",
    "Kajdacs",
    "Kölesd",
    "Tengelic",
    "Szedres",
    "Medina",
    "Belecska",
    "Keszőhidegkút",
    "Szárazd",
    "Gyönk",
    "Miszla",
    "Udvari",
    "Varsád",
    "Kistormás",
    "Szakadát",
    "Diósberény",
    "Simontornya",
    "Kisszékely",
    "Tolnanémedi",
    "Pincehely",
    "Nagyszékely",
    "Ozora",
    "Fürged",
    "Tamási",
    "Pári",
    "Nagykónyi",
    "Értény",
    "Koppányszántó",
    "Iregszemcse",
    "Újireg",
    "Nagyszokoly",
    "Magyarkeszi",
    "Felsőnyék",
    "Szekszárd",
    "Szálka",
    "Kakasd",
    "Tolna",
    "Bogyiszló",
    "Fadd",
    "Gerjen",
    "Dunaszentgyörgy",
    "Fácánkert",
    "Bátaszék",
    "Pörböly",
    "Őcsény",
    "Decs",
    "Sárpilis",
    "Várdomb",
    "Alsónána",
    "Alsónyék",
    "Báta",
    "Bonyhád",
    "Bonyhádvarasd",
    "Kisdorog",
    "Cikó",
    "Grábóc",
    "Mőcsény",
    "Bátaapáti",
    "Mórágy",
    "Sióagárd",
    "Harc",
    "Zomba",
    "Kéty",
    "Felsőnána",
    "Murga",
    "Tevel",
    "Závod",
    "Kisvejke",
    "Lengyel",
    "Mucsfa",
    "Aparhant",
    "Nagyvejke",
    "Szárász",
    "Hőgyész",
    "Szakály",
    "Regöly",
    "Kalaznó",
    "Mucsi",
    "Dombóvár",
    "Dalmand",
    "Kocsola",
    "Szakcs",
    "Lápafő",
    "Várong",
    "Nak",
    "Dúzs",
    "Csibrák",
    "Kurd",
    "Gyulaj",
    "Döbrököz",
    "Kapospula",
    "Attala",
    "Csoma",
    "Szabadi",
    "Nagyberki",
    "Kercseliget",
    "Mosdós",
    "Baté",
    "Kaposkeresztúr",
    "Taszár",
    "Kaposhomok",
    "Fonó",
    "Gölle",
    "Büssü",
    "Kazsok",
    "Igal",
    "Somogyszil",
    "Gadács",
    "Kisgyalán",
    "Bonnya",
    "Kisbárapáti",
    "Fiad",
    "Somogyacsa",
    "Somogydöröcske",
    "Törökkoppány",
    "Kára",
    "Szorosad",
    "Komló",
    "Mánfa",
    "Mecsekpölöske",
    "Liget",
    "Magyaregregy",
    "Kárász",
    "Vékény",
    "Szalatnak",
    "Köblény",
    "Csikóstőttős",
    "Mágocs",
    "Nagyhajmás",
    "Mekényes",
    "Alsómocsolád",
    "Bikal",
    "Egyházaskozár",
    "Hegyhátmaróc",
    "Tófű",
    "Szászvár",
    "Máza",
    "Györe",
    "Izmény",
    "Váralja",
    "Nagymányok",
    "Kismányok",
    "Jágónak",
    "Kaposszekcső",
    "Vásárosdombó",
    "Gerényes",
    "Tarrós",
    "Sásd",
    "Felsőegerszeg",
    "Meződ",
    "Oroszló",
    "Palé",
    "Varga",
    "Vázsnok",
    "Kisvaszar",
    "Ág",
    "Tékes",
    "Tormás",
    "Baranyaszentgyörgy",
    "Szágy",
    "Baranyajenő",
    "Gödre",
    "Mindszentgodisa",
    "Kisbeszterce",
    "Kishajmás",
    "Bakóca",
    "Magyarhertelend",
    "Bodolyabér",
    "Magyarszék",
    "Kaposvár",
    "Zselickislak",
    "Juta",
    "Hetes",
    "Csombárd",
    "Mezőcsokonya",
    "Somogysárd",
    "Újvárfalva",
    "Bodrog",
    "Magyaregres",
    "Várda",
    "Somogyjád",
    "Alsóbogát",
    "Edde",
    "Osztopán",
    "Somogyaszaló",
    "Mernye",
    "Somodor",
    "Somogygeszti",
    "Felsőmocsolád",
    "Ecseny",
    "Polány",
    "Orci",
    "Magyaratád",
    "Patalom",
    "Ráksi",
    "Szentgáloskér",
    "Zimány",
    "Szentbalázs",
    "Cserénfa",
    "Gálosfa",
    "Hajmás",
    "Kaposgyarmat",
    "Simonfa",
    "Zselicszentpál",
    "Bőszénfa",
    "Kaposszerdahely",
    "Szenna",
    "Patca",
    "Szilvásszentmárton",
    "Zselickisfalud",
    "Bárdudvarnok",
    "Sántos",
    "Nagyatád",
    "Ötvöskónyi",
    "Mike",
    "Rinyaszentkirály",
    "Tarany",
    "Somogyudvarhely",
    "Berzence",
    "Bolhás",
    "Kaposmérő",
    "Kaposújlak",
    "Kaposfő",
    "Kisasszond",
    "Kiskorpád",
    "Jákó",
    "Csököly",
    "Gige",
    "Rinyakovácsi",
    "Kadarkút",
    "Kőkút",
    "Hencse",
    "Hedrehely",
    "Visnye",
    "Lad",
    "Patosfa",
    "Homokszentgyörgy",
    "Kálmáncsa",
    "Szulok",
    "Kutas",
    "Kisbajom",
    "Beleg",
    "Szabás",
    "Nagykorpád",
    "Lábod",
    "Rinyabesenyő",
    "Görgeteg",
    "Csokonyavisonta",
    "Rinyaújlak",
    "Nagybajom",
    "Pálmajor",
    "Segesd",
    "Somogyszob",
    "Kaszó",
    "Barcs",
    "Komlósd",
    "Péterhida",
    "Babócsa",
    "Rinyaújnép",
    "Somogyaracs",
    "Háromfa",
    "Bakháza",
    "Bolhó",
    "Heresznye",
    "Vízvár",
    "Bélavár",
    "Pécs",
    "Kökény",
    "Erzsébet",
    "Kátoly",
    "Kékesd",
    "Szellő",
    "Máriakéménd",
    "Berkesd",
    "Pereked",
    "Szilágy",
    "Pogány",
    "Keszü",
    "Gyód",
    "Bicsérd",
    "Aranyosgadány",
    "Zók",
    "Boda",
    "Kővágószőlős",
    "Cserkút",
    "Bakonya",
    "Kővágótöttös",
    "Orfű",
    "Abaliget",
    "Husztót",
    "Kovácsszénája",
    "Hetvehely",
    "Okorvölgy",
    "Szentkatalin",
    "Bükkösd",
    "Helesfa",
    "Cserdi",
    "Dinnyeberki",
    "Hosszúhetény",
    "Mecseknádasd",
    "Óbánya",
    "Ófalu",
    "Hidas",
    "Mohács",
    "Bár",
    "Dunaszekcső",
    "Homorúd",
    "Kölked",
    "Udvar",
    "Pécsvárad",
    "Apátvarasd",
    "Lovászhetény",
    "Martonfa",
    "Zengővárkony",
    "Erdősmecske",
    "Feked",
    "Szebény",
    "Véménd",
    "Palotabozsok",
    "Somberek",
    "Görcsönydoboka",
    "Nagypall",
    "Fazekasboda",
    "Geresdlak",
    "Maráza",
    "Himesháza",
    "Erdősmárok",
    "Szűr",
    "Székelyszabar",
    "Nagykozár",
    "Bogád",
    "Romonya",
    "Ellend",
    "Olasz",
    "Hásságy",
    "Belvárdgyula",
    "Birján",
    "Szederkény",
    "Monyoród",
    "Versend",
    "Szajk",
    "Bóly",
    "Töttös",
    "Borjád",
    "Kisbudmér",
    "Nagybudmér",
    "Pócsa",
    "Babarc",
    "Liptód",
    "Lánycsók",
    "Kisnyárád",
    "Kozármisleny",
    "Lothárd",
    "Magyarsarlós",
    "Pécsudvard",
    "Egerág",
    "Áta",
    "Kisherend",
    "Szemely",
    "Szőkéd",
    "Újpetre",
    "Kiskassa",
    "Peterd",
    "Pécsdevecser",
    "Vokány",
    "Kistótfalu",
    "Palkonya",
    "Villánykövesd",
    "Ivánbattyán",
    "Villány",
    "Kisjakabfalva",
    "Márok",
    "Magyarbóly",
    "Illocska",
    "Kislippó",
    "Lapáncsa",
    "Lippó",
    "Ivándárda",
    "Sárok",
    "Bezedek",
    "Majs",
    "Nagynyárád",
    "Sátorhely",
    "Siklós",
    "Kisharsány",
    "Nagytótfalu",
    "Szalánta",
    "Bisse",
    "Bosta",
    "Csarnóta",
    "Szilvás",
    "Túrony",
    "Garé",
    "Szava",
    "Ócsárd",
    "Babarcszőlős",
    "Kisdér",
    "Siklósbodony",
    "Harkány",
    "Diósviszló",
    "Márfa",
    "Rádfalva",
    "Nagyharsány",
    "Siklósnagyfalu",
    "Kistapolca",
    "Egyházasharaszti",
    "Old",
    "Alsószentmárton",
    "Beremend",
    "Kásád",
    "Pellérd",
    "Görcsöny",
    "Regenye",
    "Szőke",
    "Baksa",
    "Tengeri",
    "Téseny",
    "Bogádmindszent",
    "Ózdfalu",
    "Hegyszentmárton",
    "Vajszló",
    "Besence",
    "Hirics",
    "Lúzsok",
    "Nagycsány",
    "Páprád",
    "Piskó",
    "Vejti",
    "Zaláta",
    "Kemse",
    "Sámod",
    "Adorjás",
    "Baranyahídvég",
    "Kisszentmárton",
    "Kórós",
    "Kémes",
    "Cún",
    "Drávapiski",
    "Szaporca",
    "Tésenfa",
    "Drávacsepely",
    "Kovácshida",
    "Drávaszerdahely",
    "Ipacsfa",
    "Drávacsehi",
    "Drávapalkonya",
    "Drávaszabolcs",
    "Gordisa",
    "Matty",
    "Szigetvár",
    "Botykapeterd",
    "Csertő",
    "Nagypeterd",
    "Nyugotszenterzsébet",
    "Nagyváty",
    "Szentdénes",
    "Rózsafa",
    "Bánfa",
    "Katádfa",
    "Dencsháza",
    "Szentegát",
    "Lakócsa",
    "Szentborbás",
    "Tótújfalu",
    "Somogyhatvan",
    "Somogyapáti",
    "Basal",
    "Patapoklosi",
    "Somogyviszló",
    "Somogyhárságy",
    "Magyarlukafa",
    "Vásárosbéc",
    "Mozsgó",
    "Almáskeresztúr",
    "Szulimán",
    "Almamellék",
    "Ibafa",
    "Csebény",
    "Horváthertelend",
    "Szentlászló",
    "Boldogasszonyfa",
    "Szentlőrinc",
    "Csonkamindszent",
    "Kacsóta",
    "Szabadszentkirály",
    "Gerde",
    "Pécsbagota",
    "Velény",
    "Királyegyháza",
    "Magyarmecske",
    "Gilvánfa",
    "Gyöngyfa",
    "Kisasszonyfa",
    "Magyartelek",
    "Okorág",
    "Kákics",
    "Sellye",
    "Drávaiványi",
    "Drávasztára",
    "Marócsa",
    "Sósvertike",
    "Sumony",
    "Csányoszró",
    "Bogdása",
    "Drávafok",
    "Drávakeresztúr",
    "Markóc",
    "Felsőszentmárton",
    "Hobol",
    "Gyöngyösmellék",
    "Teklafalu",
    "Bürüs",
    "Endrőc",
    "Várad",
    "Kétújfalu",
    "Zádor",
    "Szörény",
    "Kastélyosdombó",
    "Drávagárdony",
    "Potony",
    "Drávatamási",
    "Pettend",
    "Nemeske",
    "Kistamási",
    "Merenye",
    "Molvány",
    "Tótszentgyörgy",
    "Nagydobsza",
    "Kisdobsza",
    "Istvándi",
    "Darány",
    "Székesfehérvár",
    "Csór",
    "Moha",
    "Iszkaszentgyörgy",
    "Kincsesbánya",
    "Isztimér",
    "Bakonykúti",
    "Sárkeresztes",
    "Fehérvárcsurgó",
    "Bodajk",
    "Balinka",
    "Bakonycsernye",
    "Mór",
    "Nagyveleg",
    "Pusztavám",
    "Magyaralmás",
    "Söréd",
    "Csákberény",
    "Csókakő",
    "Bodmér",
    "Zámoly",
    "Gánt",
    "Csákvár",
    "Vértesboglár",
    "Felcsút",
    "Alcsútdoboz",
    "Tabajd",
    "Vértesacsa",
    "Pátka",
    "Lovasberény",
    "Pákozd",
    "Sukoró",
    "Nadap",
    "Várpalota",
    "Pétfürdő",
    "Tés",
    "Seregélyes",
    "Zichyújfalu",
    "Tác",
    "Csősz",
    "Soponya",
    "Káloz",
    "Sárkeresztúr",
    "Sárszentágota",
    "Aba",
    "Enying",
    "Lepsény",
    "Mezőszentgyörgy",
    "Mátyásdomb",
    "Dég",
    "Lajoskomárom",
    "Mezőkomárom",
    "Szabadhídvég",
    "Úrhida",
    "Sárszentmihály",
    "Sárkeszi",
    "Nádasdladány",
    "Jenő",
    "Szabadbattyán",
    "Kőszárhegy",
    "Polgárdi",
    "Kisláng",
    "Füle",
    "Ősi",
    "Küngös",
    "Csajág",
    "Balatonfőkajár",
    "Balatonvilágos",
    "Balatonakarattya",
    "Balatonkenese",
    "Balatonfűzfő",
    "Berhida",
    "Papkeszi",
    "Öskü",
    "Hajmáskér",
    "Sóly",
    "Vilonya",
    "Királyszentistván",
    "Litér",
    "Veszprém",
    "Balatonalmádi",
    "Szentkirályszabadja",
    "Alsóörs",
    "Felsőörs",
    "Lovas",
    "Csopak",
    "Paloznak",
    "Balatonfüred",
    "Balatonszőlős",
    "Tihany",
    "Aszófő",
    "Balatonudvari",
    "Örvényes",
    "Balatonakali",
    "Dörgicse",
    "Pécsely",
    "Vászoly",
    "Tótvázsony",
    "Hidegkút",
    "Nemesvámos",
    "Veszprémfajsz",
    "Zánka",
    "Balatonszepezd",
    "Révfülöp",
    "Kővágóörs",
    "Kékkút",
    "Balatonrendes",
    "Ábrahámhegy",
    "Salföld",
    "Badacsonytomaj",
    "Badacsonytördemic",
    "Szigliget",
    "Hegymagas",
    "Mencshely",
    "Szentantalfa",
    "Balatoncsicsó",
    "Óbudavár",
    "Szentjakabfa",
    "Tagyon",
    "Monoszló",
    "Köveskál",
    "Balatonhenye",
    "Szentbékkálla",
    "Mindszentkálla",
    "Káptalantóti",
    "Nemesgulács",
    "Kisapáti",
    "Gyulakeszi",
    "Nagyvázsony",
    "Barnag",
    "Pula",
    "Vöröstó",
    "Öcs",
    "Kapolcs",
    "Vigántpetend",
    "Taliándörögd",
    "Monostorapáti",
    "Hegyesd",
    "Tapolca",
    "Raposka",
    "Zalahaláp",
    "Sáska",
    "Nemesvita",
    "Balatonederics",
    "Balatongyörök",
    "Vonyarcvashegy",
    "Gyenesdiás",
    "Várvölgy",
    "Vállus",
    "Lesencefalu",
    "Lesencetomaj",
    "Lesenceistvánd",
    "Uzsa",
    "Sümeg",
    "Mihályfa",
    "Kisvásárhely",
    "Szalapa",
    "Óhíd",
    "Zalaerdőd",
    "Hetyefő",
    "Dabronc",
    "Gógánfa",
    "Ukk",
    "Rigács",
    "Megyer",
    "Zalameggyes",
    "Zalagyömörő",
    "Sümegprága",
    "Bazsi",
    "Zalaszántó",
    "Vindornyalak",
    "Karmacs",
    "Vindornyafok",
    "Zalaköveskút",
    "Vindornyaszőlős",
    "Kisgörbő",
    "Nagygörbő",
    "Sümegcsehi",
    "Döbröce",
    "Keszthely",
    "Nemesbük",
    "Cserszegtomaj",
    "Rezi",
    "Hévíz",
    "Sármellék",
    "Zalavár",
    "Szentgyörgyvár",
    "Alsópáhok",
    "Felsőpáhok",
    "Ajka",
    "Úrkút",
    "Eplény",
    "Olaszfalu",
    "Nagyesztergár",
    "Dudar",
    "Csetény",
    "Bakonyoszlop",
    "Csesznek",
    "Zirc",
    "Bakonynána",
    "Szápár",
    "Jásd",
    "Lókút",
    "Pénzesgyőr",
    "Bakonybél",
    "Borzavár",
    "Porva",
    "Bakonyszentkirály",
    "Bakonyszentlászló",
    "Fenyőfő",
    "Bakonygyirót",
    "Románd",
    "Gic",
    "Veszprémvarsány",
    "Sikátor",
    "Herend",
    "Márkó",
    "Hárskút",
    "Bánd",
    "Szentgál",
    "Városlőd",
    "Csehbánya",
    "Kislőd",
    "Magyarpolány",
    "Halimba",
    "Szőc",
    "Nyirád",
    "Pusztamiske",
    "Noszlop",
    "Bakonypölöske",
    "Oroszi",
    "Devecser",
    "Kolontár",
    "Kamond",
    "Káptalanfa",
    "Bodorfa",
    "Nemeshany",
    "Gyepükaján",
    "Csabrendek",
    "Veszprémgalsa",
    "Hosztót",
    "Szentimrefalva",
    "Zalaszegvár",
    "Tüskevár",
    "Apácatorna",
    "Kisberzseny",
    "Somlójenő",
    "Borszörcsök",
    "Somlóvásárhely",
    "Doba",
    "Somlószőlős",
    "Kisszőlős",
    "Nagyalásony",
    "Somlóvecse",
    "Vid",
    "Dabrony",
    "Karakószörcsök",
    "Kerta",
    "Iszkáz",
    "Kiscsősz",
    "Csögle",
    "Nagypirit",
    "Kispirit",
    "Adorjánháza",
    "Egeralja",
    "Pápa",
    "Nyárád",
    "Mihályháza",
    "Mezőlak",
    "Békás",
    "Kemeneshőgyész",
    "Magyargencs",
    "Kemenesszentpéter",
    "Nagyacsád",
    "Nemesgörzsöny",
    "Egyházaskesző",
    "Várkesző",
    "Marcaltő",
    "Malomsok",
    "Takácsi",
    "Vaszar",
    "Gecse",
    "Nagygyimót",
    "Vanyola",
    "Lovászpatona",
    "Nagydém",
    "Bakonytamási",
    "Pápateszér",
    "Bakonyszentiván",
    "Bakonyság",
    "Csót",
    "Adásztevel",
    "Nagytevel",
    "Homokbödöge",
    "Ugod",
    "Béb",
    "Bakonykoppány",
    "Bakonyszücs",
    "Bakonyjákó",
    "Németbánya",
    "Farkasgyepű",
    "Nóráp",
    "Dáka",
    "Pápadereske",
    "Pápasalamon",
    "Kup",
    "Pápakovácsi",
    "Ganna",
    "Döbrönte",
    "Siófok",
    "Nyim",
    "Balatonendréd",
    "Bálványos",
    "Kőröshegy",
    "Kereki",
    "Pusztaszemes",
    "Zamárdi",
    "Szántód",
    "Balatonföldvár",
    "Balatonszárszó",
    "Szólád",
    "Teleki",
    "Kötcse",
    "Nagycsepely",
    "Balatonboglár",
    "Ordacsehi",
    "Balatonszemes",
    "Balatonőszöd",
    "Balatonlelle",
    "Fonyód",
    "Balatonfenyves",
    "Balatonmáriafürdő",
    "Balatonkeresztúr",
    "Balatonberény",
    "Balatonszabadi",
    "Siójut",
    "Ádánd",
    "Ságvár",
    "Som",
    "Nagyberény",
    "Bábonymegyer",
    "Tab",
    "Lulla",
    "Sérsekszőlős",
    "Torvaj",
    "Zala",
    "Bedegkér",
    "Somogyegres",
    "Kánya",
    "Tengőd",
    "Miklósi",
    "Kapoly",
    "Zics",
    "Somogymeggyes",
    "Nágocs",
    "Andocs",
    "Karád",
    "Látrány",
    "Visz",
    "Somogytúr",
    "Somogybabod",
    "Gamás",
    "Szőlősgyörök",
    "Gyugy",
    "Lengyeltóti",
    "Kisberény",
    "Hács",
    "Buzsák",
    "Táska",
    "Öreglak",
    "Somogyvár",
    "Pamuk",
    "Somogyvámos",
    "Marcali",
    "Csömend",
    "Somogyszentpál",
    "Nikla",
    "Pusztakovácsi",
    "Libickozma",
    "Somogyfajsz",
    "Balatonszentgyörgy",
    "Vörs",
    "Balatonújlak",
    "Kéthely",
    "Kelevíz",
    "Gadány",
    "Mesztegnyő",
    "Hosszúvíz",
    "Szenyér",
    "Nemeskisfalud",
    "Tapsony",
    "Böhönye",
    "Vése",
    "Nemesdéd",
    "Varászló",
    "Inke",
    "Iharosberény",
    "Iharos",
    "Somogycsicsó",
    "Pogányszentpéter",
    "Hollád",
    "Tikos",
    "Sávoly",
    "Főnyed",
    "Szegerdő",
    "Somogysámson",
    "Somogyzsitfa",
    "Csákány",
    "Szőkedencs",
    "Somogysimonyi",
    "Nemesvid",
    "Nagyszakácsi",
    "Zalaapáti",
    "Bókaháza",
    "Esztergályhorváti",
    "Zalaszabar",
    "Orosztony",
    "Kerecseny",
    "Nagyrada",
    "Garabonc",
    "Zalamerenye",
    "Zalakaros",
    "Zalakomár",
    "Balatonmagyaród",
    "Galambok",
    "Nagyrécse",
    "Csapi",
    "Kisrécse",
    "Zalasárszeg",
    "Pacsa",
    "Zalaigrice",
    "Szentpéterúr",
    "Gétye",
    "Dióskál",
    "Zalaszentmárton",
    "Egeraracsa",
    "Felsőrajk",
    "Alsórajk",
    "Pötréte",
    "Hahót",
    "Zalaszentbalázs",
    "Börzönce",
    "Pölöskefő",
    "Kacorlak",
    "Gelse",
    "Gelsesziget",
    "Kilimán",
    "Magyarszerdahely",
    "Bocska",
    "Magyarszentmiklós",
    "Hosszúvölgy",
    "Fűzvölgy",
    "Homokkomárom",
    "Újudvar",
    "Zalacsány",
    "Ligetfalva",
    "Tilaj",
    "Kehidakustány",
    "Kallósd",
    "Zalaszentlászló",
    "Sénye",
    "Zalaszentgrót",
    "Zalavég",
    "Tekenye",
    "Türje",
    "Batyk",
    "Zalabér",
    "Pakod",
    "Dötk",
    "Nagykanizsa",
    "Nagybakónak",
    "Zalaújlak",
    "Sand",
    "Miháld",
    "Pat",
    "Zalaszentjakab",
    "Liszó",
    "Murakeresztúr",
    "Fityeház",
    "Csurgó",
    "Csurgónagymarton",
    "Szenta",
    "Gyékényes",
    "Zákány",
    "Zákányfalu",
    "Őrtilos",
    "Belezna",
    "Surd",
    "Nemespátró",
    "Porrog",
    "Porrogszentkirály",
    "Porrogszentpál",
    "Somogybükkösd",
    "Szepetnek",
    "Semjénháza",
    "Molnári",
    "Tótszerdahely",
    "Tótszentmárton",
    "Becsehely",
    "Petrivente",
    "Letenye",
    "Kistolmács",
    "Murarátka",
    "Zajk",
    "Muraszemenye",
    "Szentmargitfalva",
    "Csörnyeföld",
    "Dobri",
    "Kerkaszentkirály",
    "Tormafölde",
    "Tornyiszentmiklós",
    "Lovászi",
    "Szécsisziget",
    "Kerkateskánd",
    "Sormás",
    "Eszteregnye",
    "Rigyác",
    "Borsfa",
    "Valkonya",
    "Oltárc",
    "Bázakerettye",
    "Lasztonya",
    "Lispeszentadorján",
    "Kiscsehi",
    "Maróc",
    "Bánokszentgyörgy",
    "Várfölde",
    "Szentliszló",
    "Bucsuta",
    "Pusztamagyaród",
    "Pusztaszentlászló",
    "Söjtör",
    "Zalaegerszeg",
    "Nagykutas",
    "Kiskutas",
    "Kispáli",
    "Nagypáli",
    "Egervár",
    "Gősfa",
    "Lakhegy",
    "Vasboldogasszony",
    "Nemesrádó",
    "Milejszeg",
    "Csonkahegyhát",
    "Németfalu",
    "Kustánszeg",
    "Zalaszentiván",
    "Alibánfa",
    "Pethőhenye",
    "Zalaszentlőrinc",
    "Nemesapáti",
    "Alsónemesapáti",
    "Búcsúszentlászló",
    "Nemessándorháza",
    "Nemesszentandrás",
    "Kisbucsa",
    "Nemeshetés",
    "Pölöske",
    "Kemendollár",
    "Vöckönd",
    "Pókaszepetk",
    "Gyűrűs",
    "Zalaistvánd",
    "Bezeréd",
    "Nagykapornak",
    "Almásháza",
    "Misefa",
    "Orbányosfa",
    "Padár",
    "Zalaszentmihály",
    "Bocfölde",
    "Csatár",
    "Sárhida",
    "Bak",
    "Tófej",
    "Baktüttös",
    "Pusztaederics",
    "Zalatárnok",
    "Szentkozmadombja",
    "Nova",
    "Barlahida",
    "Mikekarácsonyfa",
    "Gutorfölde",
    "Csertalakos",
    "Szentpéterfölde",
    "Ortaháza",
    "Páka",
    "Kányavár",
    "Pördefölde",
    "Csömödér",
    "Hernyék",
    "Kissziget",
    "Zebecke",
    "Iklódbördőce",
    "Lenti",
    "Gosztola",
    "Gáborjánháza",
    "Bödeháza",
    "Szijártóháza",
    "Zalaszombatfa",
    "Zalabaksa",
    "Kerkabarabás",
    "Csesztreg",
    "Alsószenterzsébet",
    "Felsőszenterzsébet",
    "Kerkafalva",
    "Kerkakutas",
    "Magyarföld",
    "Ramocsa",
    "Szentgyörgyvölgy",
    "Nemesnép",
    "Márokföld",
    "Resznek",
    "Baglad",
    "Lendvajakabfa",
    "Rédics",
    "Belsősárd",
    "Külsősárd",
    "Lendvadedes",
    "Gellénháza",
    "Lickóvadamos",
    "Nagylengyel",
    "Babosdöbréte",
    "Ormándlak",
    "Petrikeresztúr",
    "Gombosszeg",
    "Iborfia",
    "Becsvölgye",
    "Pórszombat",
    "Pusztaapáti",
    "Szilvágy",
    "Kálócfa",
    "Kozmadombja",
    "Dobronhegy",
    "Pálfiszeg",
    "Teskánd",
    "Böde",
    "Hottó",
    "Bagod",
    "Boncodfölde",
    "Hagyárosbörönd",
    "Zalaboldogfa",
    "Zalaszentgyörgy",
    "Kávás",
    "Salomvár",
    "Keménfa",
    "Zalacséb",
    "Zalaháshágy",
    "Vaspör",
    "Ozmánbük",
    "Zalalövő",
    "Csöde",
    "Győr",
    "Vámosszabadi",
    "Kisbajcs",
    "Vének",
    "Nagybajcs",
    "Gönyű",
    "Nagyszentjános",
    "Bőny",
    "Rétalap",
    "Győrújbarát",
    "Nyúl",
    "Écs",
    "Győrság",
    "Pázmándfalu",
    "Töltéstava",
    "Bakonypéterd",
    "Lázi",
    "Pannonhalma",
    "Ravazd",
    "Tarjánpuszta",
    "Győrasszonyfa",
    "Tápszentmiklós",
    "Táp",
    "Nyalka",
    "Mezőörs",
    "Pér",
    "Tét",
    "Tényő",
    "Sokorópátka",
    "Koroncó",
    "Győrszemere",
    "Felpéc",
    "Kajárpéc",
    "Gyömöre",
    "Szerecseny",
    "Gyarmat",
    "Csikvánd",
    "Mórichida",
    "Árpás",
    "Kisbabot",
    "Rábaszentmiklós",
    "Bodonhely",
    "Rábaszentmihály",
    "Rábacsécsény",
    "Mérges",
    "Ikrény",
    "Rábapatona",
    "Enese",
    "Kóny",
    "Bágyogszovát",
    "Rábapordány",
    "Dör",
    "Abda",
    "Börcs",
    "Öttevény",
    "Mosonszentmiklós",
    "Lébény",
    "Győrsövényház",
    "Bezi",
    "Fehértó",
    "Markotabödöge",
    "Rábcakapi",
    "Cakóháza",
    "Tárnokréti",
    "Bősárkány",
    "Acsalag",
    "Barbacs",
    "Maglóca",
    "Győrújfalu",
    "Győrzámoly",
    "Győrladamér",
    "Dunaszeg",
    "Dunaszentpál",
    "Mecsér",
    "Ásványráró",
    "Hédervár",
    "Kimle",
    "Károlyháza",
    "Kunsziget",
    "Mosonmagyaróvár",
    "Feketeerdő",
    "Levél",
    "Hegyeshalom",
    "Bezenye",
    "Rajka",
    "Dunakiliti",
    "Dunasziget",
    "Halászi",
    "Máriakálnok",
    "Darnózseli",
    "Lipót",
    "Kisbodak",
    "Püski",
    "Dunaremete",
    "Jánossomorja",
    "Várbalog",
    "Újrónafő",
    "Mosonszolnok",
    "Mosonudvar",
    "Csorna",
    "Pásztori",
    "Szilsárkány",
    "Rábacsanak",
    "Egyed",
    "Sobor",
    "Rábaszentandrás",
    "Szany",
    "Farád",
    "Rábatamási",
    "Jobaháza",
    "Bogyoszló",
    "Potyond",
    "Sopronnémeti",
    "Szil",
    "Vág",
    "Rábasebes",
    "Kapuvár",
    "Kisfalud",
    "Mihályi",
    "Beled",
    "Edve",
    "Vásárosfalu",
    "Rábakecöl",
    "Páli",
    "Magyarkeresztúr",
    "Vadosfa",
    "Zsebeháza",
    "Babót",
    "Veszkény",
    "Szárföld",
    "Osli",
    "Hövej",
    "Himod",
    "Gyóró",
    "Cirák",
    "Dénesfa",
    "Vitnyéd",
    "Csapod",
    "Pusztacsalád",
    "Iván",
    "Répceszemere",
    "Csáfordjánosfa",
    "Csér",
    "Sopron",
    "Fertőrákos",
    "Harka",
    "Ágfalva",
    "Fertőd",
    "Sarród",
    "Fertőszéplak",
    "Hegykő",
    "Agyagosszergény",
    "Fertőendréd",
    "Petőháza",
    "Fertőszentmiklós",
    "Röjtökmuzsaj",
    "Ebergőc",
    "Lövő",
    "Völcsej",
    "Sopronhorpács",
    "Und",
    "Nemeskér",
    "Újkér",
    "Egyházasfalu",
    "Szakony",
    "Gyalóka",
    "Répcevis",
    "Zsira",
    "Pinnye",
    "Nagylózs",
    "Sopronkövesd",
    "Pereszteg",
    "Nagycenk",
    "Hidegség",
    "Fertőhomok",
    "Fertőboz",
    "Kópháza",
    "Celldömölk",
    "Kemenesmihályfa",
    "Ostffyasszonyfa",
    "Csönge",
    "Kenyeri",
    "Pápoc",
    "Vönöck",
    "Kemenessömjén",
    "Kemenesszentmárton",
    "Kemenesmagasi",
    "Szergény",
    "Mersevát",
    "Külsővat",
    "Nemesszalók",
    "Marcalgergelyi",
    "Vinár",
    "Boba",
    "Nemeskocs",
    "Kemenespálfa",
    "Jánosháza",
    "Karakó",
    "Nemeskeresztúr",
    "Keléd",
    "Mesteri",
    "Vásárosmiske",
    "Köcsk",
    "Kemeneskápolna",
    "Egyházashetye",
    "Borgáta",
    "Kissomlyó",
    "Duka",
    "Nagysimonyi",
    "Tokorcs",
    "Sárvár",
    "Csénye",
    "Bögöt",
    "Porpác",
    "Ölbő",
    "Szeleste",
    "Répceszentgyörgy",
    "Chernelházadamonya",
    "Bő",
    "Gór",
    "Hegyfalu",
    "Sajtoskál",
    "Simaság",
    "Lócs",
    "Iklanberény",
    "Zsédeny",
    "Pósfa",
    "Rábapaty",
    "Jákfa",
    "Uraiújfalu",
    "Nick",
    "Répcelak",
    "Csánig",
    "Vasegerszeg",
    "Tompaládony",
    "Mesterháza",
    "Nemesládony",
    "Nagygeresd",
    "Vámoscsalád",
    "Sitke",
    "Gérce",
    "Káld",
    "Vashosszúfalu",
    "Bögöte",
    "Hosszúpereszteg",
    "Sótony",
    "Nyőgér",
    "Bejcgyertyános",
    "Egervölgy",
    "Szemenye",
    "Szombathely",
    "Gencsapáti",
    "Perenye",
    "Gyöngyösfalu",
    "Lukácsháza",
    "Kőszegszerdahely",
    "Cák",
    "Kőszegdoroszló",
    "Velem",
    "Bozsok",
    "Kőszeg",
    "Horvátzsidány",
    "Kiszsidány",
    "Ólmod",
    "Peresznye",
    "Csepreg",
    "Tormásliget",
    "Bük",
    "Tömörd",
    "Nemescsó",
    "Kőszegpaty",
    "Pusztacsó",
    "Vassurány",
    "Salköveskút",
    "Söpte",
    "Vasasszonyfa",
    "Meszlen",
    "Acsád",
    "Vasszilvágy",
    "Vát",
    "Nemesbőd",
    "Vép",
    "Bozzai",
    "Kenéz",
    "Pecöl",
    "Megyehíd",
    "Ikervár",
    "Meggyeskovácsi",
    "Táplánszentkereszt",
    "Tanakajd",
    "Vasszécseny",
    "Csempeszkopács",
    "Rum",
    "Rábatöttös",
    "Zsennye",
    "Balogunyom",
    "Kisunyom",
    "Sorokpolány",
    "Sorkifalud",
    "Gyanógeregye",
    "Sorkikápolna",
    "Nemeskolta",
    "Püspökmolnári",
    "Rábahídvég",
    "Egyházashollós",
    "Nemesrempehollós",
    "Egyházasrádóc",
    "Rádóckölked",
    "Harasztifalu",
    "Nagykölked",
    "Sé",
    "Torony",
    "Dozmat",
    "Bucsu",
    "Narda",
    "Felsőcsatár",
    "Vaskeresztes",
    "Pornóapáti",
    "Horvátlövő",
    "Nárai",
    "Ják",
    "Szentpéterfa",
    "Vasvár",
    "Andrásfa",
    "Telekes",
    "Gersekarát",
    "Sárfimizdó",
    "Halastó",
    "Győrvár",
    "Hegyhátszentpéter",
    "Pácsony",
    "Olaszfa",
    "Oszkó",
    "Petőmihályfa",
    "Bérbaltavár",
    "Nagytilaj",
    "Csehi",
    "Csehimindszent",
    "Mikosszéplak",
    "Csipkerek",
    "Kám",
    "Alsóújlak",
    "Körmend",
    "Magyarnádalja",
    "Molnaszecsőd",
    "Magyarszecsőd",
    "Szarvaskend",
    "Döröske",
    "Nagymizdó",
    "Döbörhegy",
    "Nádasd",
    "Hegyháthodász",
    "Hegyhátsál",
    "Katafa",
    "Halogy",
    "Daraboshegy",
    "Felsőmarác",
    "Csákánydoroszló",
    "Vasalja",
    "Pinkamindszent",
    "Kemestaródfa",
    "Ivánc",
    "Hegyhátszentmárton",
    "Viszák",
    "Őrimagyarósd",
    "Hegyhátszentjakab",
    "Felsőjánosfa",
    "Szaknyér",
    "Szőce",
    "Kisrákos",
    "Pankasz",
    "Nagyrákos",
    "Szatta",
    "Őriszentpéter",
    "Ispánk",
    "Szalafő",
    "Kondorfa",
    "Bajánsenye",
    "Kerkáskápolna",
    "Kercaszomor",
    "Magyarszombatfa",
    "Velemér",
    "Rátót",
    "Gasztony",
    "Vasszentmihály",
    "Nemesmedves",
    "Rönök",
    "Rábagyarmat",
    "Csörötnek",
    "Magyarlak",
    "Szentgotthárd",
    "Apátistvánfalva",
    "Kétvölgy",
    "Orfalu",
    "Alsószölnök",
    "Szakonyfalu",
    "Felsőszölnök"
]

const automaticLocator = async () => {
    if ("geolocation" in navigator) {
        try {
            const position = await new Promise((resolve, reject) =>
                navigator.geolocation.getCurrentPosition(resolve, reject, {
                    timeout: 5000
                })
            );
            const { latitude, longitude } = position.coords;
            
            const res = await fetch(
                `https://api.openweathermap.org/geo/1.0/reverse?lat=${latitude}&lon=${longitude}&limit=1&appid=${API_KEY}`
            );
            
            const data = await res.json();
            
            if (data.length > 0) {
                getCoords(data)
            }
            
        } catch (err) {
            console.log(err)
        }
    }
}

const renderAutomatic = async () => {
    const varos = "Budapest"
    const koordinatak = await getCoordsAutomatic(varos)
    lat = koordinatak.lat
    lon = koordinatak.lon
    renderWeather(varos)
    renderHourlyWeather(varos)
    automaticLocator()
}

const getDailyWeather = async (telepules) => {
    
    const dailyWeather = await fetch(
        `https://api.openweathermap.org/data/2.5/weather?q=${telepules}&appid=${API_KEY}&lang=hu`
    );
    return dailyWeather;
};

const getUVIndexAndDewPoint = async () => {
    const UVandDew = await fetch(
        `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,dew_point_2m,uv_index&timezone=auto`
    );
    const data = await UVandDew.json();
    
    return {
        dew_point: data.current.dew_point_2m,
        uv_index: data.current.uv_index
        
    }
}

const getMoonData = async () => {
    const data = await fetch(
        `https://api.solunar.org/solunar/lat=${lat}&lon=${lon},${new Date().toLocaleDateString('sv-SE').replaceAll('-', '')},1`
    )
    const MoonData = await data.json()
    
    return {
        moonrise: MoonData.moonRise,
        moonset: MoonData.moonSet,
        moonphase: MoonData.moonPhase
    }
}
const getCoordsAutomatic = async (e) => {   
    const varos = e
    const res = await fetch(
        `https://api.openweathermap.org/geo/1.0/direct?q=${varos}&limit=1&appid=${API_KEY}&lang=hu`
    );
    
    if (!res.ok){
        return false
    }

    const data = await res.json()
    
    if(data.length > 0)
        return {
            lat: data[0].lat,
            lon: data[0].lon
        }

    return false
}

const getCoords = async (e) => {   
    const varosInp = e.target.value
    
    talalatok.innerHTML = ""
    
    const talalat = varosok
    .filter(v => v.toLowerCase().startsWith(varosInp.toLowerCase()))
    .slice(0,5);
    
    if(talalat.length > 0){
        
        if (varosInp.length ==  0){
            talalatok.innerHTML = ""
            return
        }
        talalat.forEach(varos => {
            const div = document.createElement("div")
            div.classList.add("bg-[#82B3DB]", "hover:bg-[#476D98]", "rounded-lg", "px-2", "py-1")
            div.textContent = varos
            
            div.addEventListener("click", () => {
                renderWeather(varos)
                renderHourlyWeather(varos)
                varosInput.value = varos
                talalatok.innerHTML = ""
            })
            
            talalatok.appendChild(div)
        })
    } else {
        const res = await fetch(
            `https://api.openweathermap.org/geo/1.0/direct?q=${varosInp}&limit=5&appid=${API_KEY}&lang=hu`
        );
        const data = await res.json()
        data.forEach(varos => {
            const div = document.createElement("div")
            div.classList.add("bg-[#82B3DB]", "hover:bg-[#476D98]", "rounded-lg", "px-2", "py-1")
            div.textContent = varos.name
            
            div.addEventListener("click", () => {
                renderWeather(varos.name)
                renderHourlyWeather(varos.name)
                varosInput.value = varos.name
                talalatok.innerHTML = ""
            })
            
            talalatok.appendChild(div)
        })
    }
    
    return false
}

const varosInput = document.getElementById("varosinput")
const talalatok = document.getElementById("talalatok");
varosInput.addEventListener("input", (e) => getCoords(e));

document.onclick = (e) => {
    if (!varosInput.contains(e.target) && !talalatok.contains(e.target)) {
        talalatok.innerHTML = ""
    }
}

const renderWeather = async (telepules) => {
    const data = await getDailyWeather(telepules);
    dailyWeather = await data.json()

    const extraJellemzo = await getUVIndexAndDewPoint();
    const holdJellemzok = await getMoonData();

    // Vitamin ajánló frissítése az adatokkal (Kelvin -> Celsius konverzióval)
    vitaminAjanlo(dailyWeather.weather[0].main, dailyWeather.main.temp - 273.15, extraJellemzo.uv_index);

    //jelenlegi időjárás

    const jelenlegiDiv = document.getElementById("jelenlegi_idojaras")
    jelenlegiDiv.innerHTML = "";
    const jelenlegiDivContent = document.createElement("div")
    jelenlegiDivContent.classList.add("flex", "justify-between", "bg-[#476D98]", "p-4", "rounded-lg", "m-2", "h-auto", "h-[-webkit-fill-available]!")

    const balWrapper = document.createElement("div")
    const fok = document.createElement("h2");
    const ikon = document.createElement("img")
    const leiras = document.createElement("p")
    leiras.id = "weather-description";
    const ikonWrapper = document.createElement("div")
    const hoerzet = document.createElement("p")
    const jelenlegiJellWrapper = document.createElement("div")
    const varos = document.createElement("p")
    const ido = document.createElement("p")
    const minmax = document.createElement("p")
    const varosWrapper = document.createElement("div")
    const minmaxWrapper = document.createElement("div")

    balWrapper.classList.add("flex", "flex-col", "justify-between")
    fok.classList.add("font-bold", "text-3xl", "pl-1")
    ikon.alt = "Időjárás ikon"
    leiras.classList.add("font-bold", "pl-2")
    hoerzet.classList.add("font-bold")
    varos.classList.add("font-bold", "text-3xl", "text-right")
    ido.classList.add("font-bold", "text-right")
    minmax.classList.add("font-bold", "text-right")
    jelenlegiJellWrapper.classList.add("flex", "flex-col", "justify-between")
    ikonWrapper.classList.add("flex", "items-center")

    fok.innerHTML = hofok(dailyWeather.main.temp) + getUnitSymbol();
    fok.id = "jelenlegi_fok";
    ikon.src = `images/icons/weather/${dailyWeather.weather[0].icon}.svg`;
    ikon.classList.add("h-20")
    leiras.innerHTML = dailyWeather.weather[0].description.charAt(0).toUpperCase() + dailyWeather.weather[0].description.slice(1);
    hoerzet.innerHTML = "Hőérzet: " + hofok(dailyWeather.main.feels_like) + getUnitSymbol();
    hoerzet.id = "jelenlegi_hoerzet";
    varos.innerHTML = dailyWeather.name;
    ido.innerHTML = new Date().toLocaleTimeString("hu-HU", {hour: "2-digit", minute: "2-digit"});
    minmax.innerHTML = hofok(dailyWeather.main.temp_min) + getUnitSymbol() + "/" + hofok(dailyWeather.main.temp_max) + getUnitSymbol();
    minmax.id = "jelenlegi_minmax";

    varosWrapper.appendChild(varos)
    varosWrapper.appendChild(ido)
    minmaxWrapper.appendChild(minmax)

    balWrapper.appendChild(fok)
    ikonWrapper.appendChild(ikon)
    ikonWrapper.appendChild(leiras)
    balWrapper.appendChild(ikonWrapper)
    balWrapper.appendChild(hoerzet)

    jelenlegiJellWrapper.appendChild(varosWrapper)    
    jelenlegiJellWrapper.appendChild(minmaxWrapper)    

    jelenlegiDivContent.appendChild(balWrapper)
    jelenlegiDivContent.appendChild(jelenlegiJellWrapper)
    jelenlegiDiv.appendChild(jelenlegiDivContent)

    //napi jellemzők

    const jellemzokContainer = document.getElementById("idojaras_jellemzoi")
    jellemzokContainer.innerHTML = ""

    const jellemzokContainerContent= document.createElement("div")
    jellemzokContainerContent.classList.add("flex", "flex-col", "justify-evenly", "m-2", "p-2", "rounded-lg", "bg-[#82B3DB]", "h-[-webkit-fill-available]!")

    
    const jellemzok = [
        { nev: "Páratartalom", ertek: dailyWeather.main.humidity, egyseg: "%", icon: "/images/icons/paratartalom.svg" }, 
        { nev: "Szélsebesség", ertek: dailyWeather.wind.speed, egyseg: " km/h", icon: "/images/icons/szelsebesség.svg" },
        { nev: "UV Index", ertek: extraJellemzo.uv_index, egyseg: "", icon: "/images/icons/uv_index.svg" },
        { nev: "Légnyomás", ertek: dailyWeather.main.pressure, egyseg: " mb", icon: "/images/icons/legnyomas.svg" },
        { nev: "Látótávolság", ertek: dailyWeather.visibility/1000, egyseg: " km", icon: "/images/icons/latotavolsag.svg" },
        { nev: "Harmatpont", ertek: extraJellemzo.dew_point, egyseg: " °", icon: "/images/icons/harmatpont.svg" }
    ]
    
    const jellemzokWrapper = document.createElement("div");
    
    jellemzokWrapper.classList.add("grid", "grid-cols-2", "xl:grid-cols-3","gap-4");
    
    jellemzok.map(({ nev, ertek, egyseg }) => {
        const jellemzokDiv = document.createElement("div");
        const cim = document.createElement("h3");
        const adat = document.createElement("p");
        
        jellemzokDiv.classList.add("bg-[#476D98]", "rounded-2xl", "p-4", "text-white");
        cim.classList.add("font-bold", "mb-2");
        adat.classList.add("text-2xl", "text-center");
        
        cim.innerHTML = nev;
        adat.innerHTML = ertek + egyseg;
        
        jellemzokDiv.appendChild(cim);
        jellemzokDiv.appendChild(adat);
        jellemzokWrapper.appendChild(jellemzokDiv);
    })
    
    jellemzokContainerContent.appendChild(jellemzokWrapper)
    jellemzokContainer.appendChild(jellemzokContainerContent)

    //nap jellemzők

    const napholdWrapper = document.createElement("div");
    napholdWrapper.classList.add("flex", "flex-col")

    const sunWrapper = document.createElement("div")
    sunWrapper.classList.add("bg-[#476D98]", "rounded-lg", "my-5")

    const sunDiv = document.createElement("div")
    sunDiv.classList.add("flex", "justify-center")

    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("viewBox", "0 0 300 40");
    svg.setAttribute("class", "w-full h-25");
    svg.setAttribute("preserveAspectRatio", "xMidYMid meet");
    svg.id="sunriseSvg"

    const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("d", "M20,100 A130,130 0 0,1 280,100");
    path.setAttribute("fill", "none");
    path.setAttribute("stroke", "#d7f0ff");
    path.setAttribute("stroke-width", "3");
    svg.setAttribute("class", "w-full max-w-115 h-45");
    path.id="sunArc"

    const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    circle.setAttribute("cx", "40");
    circle.setAttribute("cy", "30");
    circle.setAttribute("r", "15");
    circle.setAttribute("fill", "#F4C542");
    circle.id="sunMarker"

    svg.appendChild(path)
    svg.appendChild(circle)
    sunDiv.appendChild(svg)

    sunWrapper.appendChild(sunDiv)

    const kelteWrapper = document.createElement("div")
    const keltetext1 = document.createElement("p")
    const keltetext2 = document.createElement("p")

    keltetext1.textContent = `${String(new Date(dailyWeather.sys.sunrise * 1000).getHours()).padStart(2, "0")}:${String(new Date(dailyWeather.sys.sunrise * 1000).getMinutes()).padStart(2, "0")}`
    keltetext2.textContent = "Napkelte"
    kelteWrapper.appendChild(keltetext1)
    kelteWrapper.appendChild(keltetext2)

    const nyugtaWrapper = document.createElement("div")
    const nyugtatext1 = document.createElement("p")
    const nyugtatext2 = document.createElement("p")

    nyugtatext1.textContent = `${String(new Date(dailyWeather.sys.sunset * 1000).getHours()).padStart(2, "2")}:${String(new Date(dailyWeather.sys.sunset * 1000).getMinutes()).padStart(2, "0")}`
    nyugtatext2.textContent = "Napnyugta"
    nyugtaWrapper.appendChild(nyugtatext1)
    nyugtaWrapper.appendChild(nyugtatext2)

    const sunTextWrapper = document.createElement("div")

    sunTextWrapper.classList.add("flex", "justify-around", "text-center")

    sunTextWrapper.appendChild(kelteWrapper)
    sunTextWrapper.appendChild(nyugtaWrapper)
    sunWrapper.appendChild(sunTextWrapper)

    napholdWrapper.appendChild(sunWrapper)

    
    //hold jellemzők
    
    const holdWrapper = document.createElement("div")
    const holdKelteDiv = document.createElement("div")
    const holdNyugtaDiv = document.createElement("div")
    const holdFazisDiv = document.createElement("div")

    const holdKelteText1 = document.createElement("p")
    const holdKelteText2 = document.createElement("p")
    const holdNyugtaText1 = document.createElement("p")
    const holdNyugtaText2 = document.createElement("p")
    const fazisKep = document.createElement("img")
    const fazistText = document.createElement("p")

    holdWrapper.classList.add("flex", "justify-evenly", "items-center", "text-center", "bg-[#476D98]", "rounded-lg", "py-5")
    holdFazisDiv.classList.add("flex", "flex-col","items-center", "px-2")

    fazisKep.src = `./images/icons/${
        holdJellemzok.moonphase.toLowerCase().replace(/\s+/g, "-")
    }-moon.svg`;
    fazisKep.classList.add("w-25", "h-auto")

    holdKelteText1.textContent = holdJellemzok.moonrise
    holdKelteText2.textContent = "Holdkelte"
    holdNyugtaText1.textContent = holdJellemzok.moonset
    holdNyugtaText2.textContent = "Holdnyugta"
    fazistText.textContent = moonPhasesHU[holdJellemzok.moonphase]

    holdKelteDiv.appendChild(holdKelteText1)
    holdKelteDiv.appendChild(holdKelteText2)
    
    holdNyugtaDiv.appendChild(holdNyugtaText1)
    holdNyugtaDiv.appendChild(holdNyugtaText2)

    holdFazisDiv.appendChild(fazisKep)
    holdFazisDiv.appendChild(fazistText)
    
    holdWrapper.appendChild(holdNyugtaDiv)
    holdWrapper.appendChild(holdFazisDiv)
    holdWrapper.appendChild(holdKelteDiv)

    napholdWrapper.appendChild(holdWrapper)
    jellemzokContainerContent.appendChild(napholdWrapper)
    
};

function sunMove () {
    const arc = document.getElementById('sunArc');
    const sun = document.getElementById('sunMarker');
    if (!arc || !sun) return;

    let sunriseTimestamp, sunsetTimestamp;
    const now = new Date().getTime();

    if (dailyWeather && dailyWeather.sys) {
        sunriseTimestamp = dailyWeather.sys.sunrise * 1000;
        sunsetTimestamp = dailyWeather.sys.sunset * 1000;
    } else {
        const d = new Date();
        sunriseTimestamp = new Date(d.setHours(6, 30, 0, 0)).getTime();
        sunsetTimestamp = new Date(d.setHours(17, 0, 0, 0)).getTime();
    }

    // Calculate progress (0 before sunrise, 1 after sunset)
    let progress;
    if (now <= sunriseTimestamp) {
        progress = 0;
    } else if (now >= sunsetTimestamp) {
        progress = 1;
    } else {
        progress = (now - sunriseTimestamp) / (sunsetTimestamp - sunriseTimestamp);
    }

    const L = arc.getTotalLength();
    const point = arc.getPointAtLength(progress * L);

    // Position sun circle (cx, cy) on the arc
    sun.setAttribute('cx', point.x);
    sun.setAttribute('cy', point.y);

    // Ensure the entire arc is visible by adjusting the SVG's viewBox dynamically
    const svg = document.getElementById('sunriseSvg');
    if (svg) {
        const padding = 20; // Add padding to ensure visibility
        const bbox = arc.getBBox();
        svg.setAttribute(
        'viewBox',
        `${bbox.x - padding} ${bbox.y - padding} ${bbox.width + 2 * padding} ${bbox.height + 2 * padding}`
        );
    }
}

const getHourlyWeather = async (telepules) => {
    const weeklyWeather = await fetch(
        `https://api.openweathermap.org/data/2.5/forecast?q=${telepules}&appid=${API_KEY}&lang=hu`
    );
    return weeklyWeather;
};

const renderHourlyWeather = async (telepules) => {
    const data = await getHourlyWeather(telepules)
    hourlyWeather = await data.json();

    //óránkénti időjárás

    const orankenti = document.getElementById("orankenti_idojaras");
    orankenti.innerHTML = "";

    const orankentiContent = document.createElement("div")
    orankentiContent.classList.add("flex", "m-2", "h-[-webkit-fill-available]!");

    const swiper = document.createElement("div");
    const swiperwrapper = document.createElement("div");

    swiper.classList.add("swiper", "w-full", "!px-5", "!py-5", "bg-[#82B3DB]", "rounded-lg");
    swiperwrapper.classList.add("swiper-wrapper");
 
    orankenti.appendChild(orankentiContent)
    orankentiContent.appendChild(swiper);
    swiper.appendChild(swiperwrapper)
 
    let id = 0;
 
    hourlyWeather.list.slice(0, 9).forEach( ora => {
        const slide = document.createElement("div");
        const oraIdo = document.createElement("p");
        const oraIkon = document.createElement("img");
        const oraLeiras = document.createElement("p");
        const oraFok = document.createElement("p");
        const oraEsoWrapper = document.createElement("div");
        const oraEsoIkon = document.createElement("img")
        const oraEso = document.createElement("p");
 
        slide.classList.add("swiper-slide", `slide${id}`, "bg-[#476D98]", "rounded-2xl", "select-none", "px-15" , "py-2","!flex", "flex-col","items-center", "justify-evenly", "!w-[120px]", "text-center")
        oraIdo.innerHTML = new Date(ora.dt * 1000).getHours() + ":00";
        oraIkon.src = `images/icons/weather/${dailyWeather.weather[0].icon}.svg`;
        oraIkon.classList.add("min-w-8");
        oraLeiras.innerHTML = ora.weather[0].description.charAt(0).toUpperCase() + ora.weather[0].description.slice(1);
        oraLeiras.classList.add("text-xs");
        rawHourlyTemps.push(ora.main.temp);
        oraFok.innerHTML = hofok(ora.main.temp) + getUnitSymbol();

        oraFok.classList.add("font-bold");
        oraEsoWrapper.classList.add("flex", "items-center")
        oraEsoIkon.src = "images/icons/water-drop.svg";
        oraEsoIkon.classList.add("max-w-[12px]", "mr-0.5");
        oraEso.innerHTML = Math.round(ora.pop * 100) + "%";

        oraEso.classList.add("text-sm");
 
 
        slide.appendChild(oraIdo);
        slide.appendChild(oraIkon);
        slide.appendChild(oraLeiras);
        slide.appendChild(oraFok);
        slide.appendChild(oraEsoIkon)
        slide.appendChild(oraEsoWrapper);
        oraEsoWrapper.appendChild(oraEsoIkon)
        oraEsoWrapper.appendChild(oraEso);
        swiperwrapper.appendChild(slide)
 
        id++;
    });
 
 
    new Swiper(".swiper", {
        slidesPerView: "auto",
        spaceBetween: 16,
        freeMode: true,      
        resistance: false,
        momentumBounce: false,
        watchOverflow: false,
    });



    //napi időjárás

    const napi = document.getElementById("napi_idojaras");
    napi.innerHTML = ""

    const napiContent = document.createElement("div")
    napiContent.classList.add("flex", "flex-col", "m-2", "col-span-2", "h-[-webkit-fill-available]!");

    napi.appendChild(napiContent)

    let napok = [];
    let esok = [];
    let ikonok = [];
    let minek = [];
    let maxok = [];

    let db = 0;
    hourlyWeather.list.forEach(nap => {
        db++;

        let esokO =  [];
        let ikonokO =  [];
        let minekO = [];
        let maxokO = [];

        esokO.push(nap.pop*100);
        ikonokO.push(nap.weather[0].icon);
        minekO.push(nap.main.temp_min);
        maxokO.push(nap.main.temp_max);


        if(db == 8){
            db = 0;

            napok.push(new Date(nap.dt * 1000).toLocaleDateString("hu-HU", {weekday: "long"}));

            esokO = esokO.reduce((a,b) => a + b, 0) / esokO.length;  
            esok.push(esokO);
            esokO = []

            ikonokO = ikonokO.sort((a,b) =>
                ikonokO.filter(v => v===a).length
                - ikonokO.filter(v => v===b).length
            ).pop();
            ikonok.push(ikonokO);


            const dayMinK = Math.min(...minekO);
            const dayMaxK = Math.max(...maxokO);
            minek.push(dayMinK);
            maxok.push(dayMaxK);
            rawDailyMin.push(dayMinK);
            rawDailyMax.push(dayMaxK);
            minekO = [];
            maxokO = [];
        }
    });

    const napDivWrapper = document.createElement("div");
    napiContent.appendChild(napDivWrapper);
    napDivWrapper.classList.add("flex", "flex-col", "lg:justify-evenly","rounded-lg","bg-[#82B3DB]", "h-[-webkit-fill-available]!");

    for (let i = 0; i < 5; i++){

        const napDiv = document.createElement("div");
        const napNev = document.createElement("p");
        const napEsoWrapper = document.createElement("div");
        const napEsoIkon = document.createElement("img")
        const napEso = document.createElement("p");
        const napIkon = document.createElement("img");
        const napminmaxWrapper = document.createElement("div")
        const napMin = document.createElement("p");
        const napMax = document.createElement("p");

        napDiv.classList.add("grid", "grid-cols-4", "bg-[#476D98]","m-2", "p-3", "rounded-lg");
        napEsoWrapper.classList.add("flex", "items-center","gap-1");
        napminmaxWrapper.classList.add("flex", "justify-end", "gap-3");
        napEsoIkon.classList.add("w-5");
        napEsoIkon.src = "images/icons/water-drop.svg";

        if (i == 0){
            napNev.innerHTML = "Ma";
        } else {
            napNev.innerHTML = napok[i].charAt(0).toUpperCase() + napok[i].slice(1);
        }
        napEso.innerHTML = Math.round(esok[i]) + "%";
        napIkon.src = `images/icons/weather/${dailyWeather.weather[0].icon}.svg`;
        napIkon.classList.add("mx-auto", "h-7")
        napMin.innerHTML = hofok(minek[i]) + getUnitSymbol();
        napMax.innerHTML = hofok(maxok[i]) + getUnitSymbol();


        napDivWrapper.appendChild(napDiv);

        napEsoWrapper.appendChild(napEsoIkon);
        napEsoWrapper.appendChild(napEso);
        
        napminmaxWrapper.appendChild(napMin);
        napminmaxWrapper.appendChild(napMax);
    
        napDiv.appendChild(napNev);
        napDiv.appendChild(napEsoWrapper)
        napDiv.appendChild(napIkon);
        napDiv.appendChild(napminmaxWrapper)

        napDivWrapper.append(napDiv)
    }
};

const changeUnit = (newUnit) => {
    unit = newUnit === "fahrenheit" ? "fahrenheit" : "celsius"; // only C/F

    const cOn = unit === "celsius";
    const fOn = unit === "fahrenheit";

    const cT = document.querySelector(".toggle-celsius");
    const fT = document.querySelector(".toggle-fahrenheit");

    cT && cT.classList.toggle("bg-[#476D98]", cOn);
    fT && fT.classList.toggle("bg-[#476D98]", fOn);

    // aktuális
    document.getElementById("jelenlegi_fok").innerHTML =
        hofok(dailyWeather.main.temp) + getUnitSymbol();

    document.getElementById("jelenlegi_hoerzet").innerHTML =
        "Hőérzet: " + hofok(dailyWeather.main.feels_like) + getUnitSymbol();

    document.getElementById("jelenlegi_minmax").innerHTML =
        hofok(dailyWeather.main.temp_min) + getUnitSymbol() +
        "/" +
        hofok(dailyWeather.main.temp_max) + getUnitSymbol();

    // óránkénti
    document.querySelectorAll(".swiper-slide .font-bold").forEach((el, i) => {
        el.innerHTML = hofok(rawHourlyTemps[i]) + getUnitSymbol();
    });

    // napi
    document.querySelectorAll("#napi_idojaras .flex.justify-end").forEach((el, i) => {
        if (!el || !el.children || el.children.length < 2) return;
        el.children[0].innerHTML = hofok(rawDailyMin[i]) + getUnitSymbol();
        el.children[1].innerHTML = hofok(rawDailyMax[i]) + getUnitSymbol();
    });
};

const getUnitSymbol = () => (unit === "fahrenheit" ? "°F" : "°C");

const hofok = (kelvin) => {
    if (typeof kelvin !== "number") return "";
    return unit === "fahrenheit"
        ? Math.round((kelvin - 273.15) * 9 / 5 + 32)
        : Math.round(kelvin - 273.15);
};

function getVitaminRecommendation(weatherData) {
    const { weather, temp, uvIndex } = weatherData;
    let vitamins = new Set();
    const w = weather ? weather.toLowerCase() : "";

    // Hőmérséklet alapú ajánlások
    if (temp < 10) {
        vitamins.add("C-vitamin");
        vitamins.add("D-vitamin");
        vitamins.add("Cink");
        vitamins.add("Omega-3"); // Téli depresszió ellen, bőr hidratálás
    } else if (temp > 25) {
        vitamins.add("Magnézium"); // Izzadás miatt
        vitamins.add("Kálium");
        vitamins.add("B-komplex"); // Energia
    }

    // Időjárás jelenség alapú
    if (w.includes("rain") || w.includes("drizzle") || w.includes("thunder")) {
        vitamins.add("C-vitamin");
        vitamins.add("E-vitamin"); // Bőr védelem
        vitamins.add("Cink");
    } else if (w.includes("snow")) {
        vitamins.add("D-vitamin");
        vitamins.add("C-vitamin");
        vitamins.add("Vas"); // Energiaszint
    } else if (w.includes("clear") || w.includes("sun")) {
        if (uvIndex > 5) {
            vitamins.add("E-vitamin"); // UV védelem
            vitamins.add("A-vitamin"); // Szem védelem
        }
    } else if (w.includes("cloud") || w.includes("fog") || w.includes("mist")) {
        vitamins.add("D-vitamin");
        vitamins.add("B-komplex"); // Hangulatjavítás
    }

    // UV Index alapú
    if (uvIndex < 3) {
        vitamins.add("D-vitamin");
    }

    // Alapértelmezett, ha nincs specifikus ajánlás
    if (vitamins.size === 0) {
        vitamins.add("C-vitamin");
        vitamins.add("Magnézium");
    }
  
    return Array.from(vitamins);
}

const vitaminAjanlo = (weather, temp, uvIndex) => {
    const ajanlottVitaminok = getVitaminRecommendation({ weather, temp, uvIndex });

    const vitaminAdatok = {
        "C-vitamin": { adag: "75-90mg", icon: "🍊" },
        "D-vitamin": { adag: "1500-2000IU", icon: "☀️" },
        "Magnézium": { adag: "300-400mg", icon: "🥑" },
        "Kálium": { adag: "3500-4700mg", icon: "🍌" },
        "Cink": { adag: "10-15mg", icon: "🥩" },
        "B-komplex": { adag: "1 tabletta", icon: "⚡" },
        "E-vitamin": { adag: "15mg", icon: "🌻" },
        "A-vitamin": { adag: "700-900µg", icon: "🥕" },
        "Omega-3": { adag: "250-500mg", icon: "🐟" },
        "Vas": { adag: "8-18mg", icon: "🥬" },
        "Kálcium": { adag: "1000mg", icon: "🥛" }
    };

    const vitaminContainer = document.getElementById("vitamin_ajanlo");
    vitaminContainer.innerHTML = "";

    const vitaminContainerContent = document.createElement("div")
    vitaminContainerContent.classList.add("w-auto", "bg-[#82B3DB]", "h-auto", "rounded-lg", "m-2", "p-2", "sm:p-4", "flex", "flex-col", "justify-evenly", "h-[-webkit-fill-available]!")
    
    const cim = document.createElement("h2")
    const vitaminWrapper = document.createElement("div");
    
    cim.textContent = "Vitamin ajánló"
    cim.classList.add("text-2xl", "sm:text-4xl", "text-center", "pb-5")
    vitaminWrapper.classList.add("text-center", "grid", "grid-cols-1", "sm:grid-cols-2", "gap-4", "lg:gap-10", "w-full");

    ajanlottVitaminok.forEach(nev => {
        const adat = vitaminAdatok[nev] || { adag: "N/A", icon: "💊" };
    
        const vitaminDiv = document.createElement("div");
        vitaminDiv.classList.add("bg-[#476D98]", "rounded-2xl", "p-4", "w-[85%]", "mx-auto", "flex", "justify-between", "items-center", "px-5");
    
        const nevWrapper = document.createElement("div");
        nevWrapper.classList.add("flex", "items-center", "gap-2");

        const iconSpan = document.createElement("span");
        iconSpan.textContent = adat.icon;
        iconSpan.classList.add("text-xl");

        const nevP = document.createElement("p");
        nevP.textContent = nev + ":";
        
        nevWrapper.appendChild(iconSpan);
        nevWrapper.appendChild(nevP);
    
        const adagP = document.createElement("p");
        adagP.classList.add("text-white", "font-bold");
        adagP.textContent = adat.adag + "/nap";
    
        vitaminDiv.appendChild(nevWrapper)
        vitaminDiv.appendChild(adagP)

        vitaminWrapper.appendChild(vitaminDiv)
    });

    vitaminContainerContent.appendChild(cim)
    vitaminContainerContent.appendChild(vitaminWrapper)
    vitaminContainer.appendChild(vitaminContainerContent)
}

renderAutomatic()
setInterval(sunMove, 60000);
sunMove();


